product: ICU
l10n_version: 1.0.1

online_service_url: http://localhost:8091
#offline_resources_base_url: file://d:/l10ntest/PythonClient/2.0.0/
# log path for the python client
log_path: ../../logs

# local storage path for caching
#cache_path: ./singleton_default/

format: default

# how many seconds should be waited to try again for accessing the remote service,
# when there is no data cached
try_delay: 10

default_locale: de
source_locale: en

# how many seconds should be waited to update cache data when there is old data existed
cache_expired_time: 60

#multitask: async