coverage:
  precision: 2        
  round: down         
  range: 20...80     
  status:
    project:                   
      default:                 
        enabled: yes           
        target: 50%                 
        if_no_uploads: error   
        if_not_found: error  
        if_ci_failed: error   
    patch:
      default:
        enabled: true            
        target: 0%                      
        if_no_uploads: error     
        if_not_found: error
        if_ci_failed: error



