codecov:
  require_ci_to_pass: false
  branch: g11n-ruby-client
  
coverage:
  status:
    project:
      default:
        target: 80%
        if_ci_failed: error
        flags:
          - g11n-ruby-client
    patch:
      default:
        target: 100%
flags:
  g11n-ruby-client:
    paths:
      - spec/ 
    carryforward: true