coverage:
  status:
    project:
      default:
        target: 80%
        if_ci_failed: error
        flags:
          - g11n-ruby-client
    patch:
      default:
        target: 100%
flags:
  g11n-cldr-pattern:
    paths:
      - spec/ 
    carryforward: true