coverage:
  status:
    project:
      default:
        target: 50%
        if_ci_failed: error
        flags:
          - g11n-cldr-pattern
    patch:
      default:
        target: 100%
flags:
  g11n-cldr-pattern:
    paths:
      - src/main/java/com/vmware/i18n/
      - !src/main/java/com/vmware/i18n/utils/CLDRUtils.java
    carryforward: true
