coverage:
  status:
    project:
      default:
        target: 50%
        if_ci_failed: error
        flags:
          - g11n-js-client
    patch:
      default:
        target: 100%
flags:
  g11n-cldr-pattern:
    paths:
      - src/ 
    carryforward: true
