//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WanderingWiFi.AirWatch.Globalization.Resources.LegacyAndroidMigration {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LabelValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WanderingWiFi.AirWatch.Globalization.Resources.LegacyAndroidMigration.LabelValues" +
                            "", typeof(LabelValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate Android 7 and Higher.
        /// </summary>
        internal static string Android7Zebra {
            get {
                return ResourceManager.GetString("Android7Zebra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration to work managed requires Zebra devices to be on Android 7 and higher. Update your devices before proceeding with migration..
        /// </summary>
        internal static string Android7ZebraDescription {
            get {
                return ResourceManager.GetString("Android7ZebraDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android enterprise user account creation failed.
        /// </summary>
        internal static string AndroidEnterpriseUserAccountCreationFailed {
            get {
                return ResourceManager.GetString("AndroidEnterpriseUserAccountCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Public Apps.
        /// </summary>
        internal static string ApprovePublicApps {
            get {
                return ResourceManager.GetString("ApprovePublicApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string CertificateUpload {
            get {
                return ResourceManager.GetString("CertificateUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your network settings to ensure a connection between Workspace ONE and the Google Play store is established. {0}.
        /// </summary>
        internal static string CheckNetworkSettings {
            get {
                return ResourceManager.GetString("CheckNetworkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the type of legacy Android migration that you would like to create..
        /// </summary>
        internal static string ChooseMigrationType {
            get {
                return ResourceManager.GetString("ChooseMigrationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Validate to retrieve count of devices eligible for migration.
        /// </summary>
        internal static string ClickValidate {
            get {
                return ResourceManager.GetString("ClickValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Not Sent.
        /// </summary>
        internal static string CommandNotSent {
            get {
                return ResourceManager.GetString("CommandNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Queued.
        /// </summary>
        internal static string CommandQueued {
            get {
                return ResourceManager.GetString("CommandQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this migration will prevent devices in queue from migrating from Legacy Android by withdrawing the persistent notification. Android Enterprise will not be removed from devices that have already migrated. Are you sure you want to delete this migration?.
        /// </summary>
        internal static string ConfirmDeleteMigrationContent {
            get {
                return ResourceManager.GetString("ConfirmDeleteMigrationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete - {0}.
        /// </summary>
        internal static string ConfirmDeleteMigrationTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteMigrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this migration?.
        /// </summary>
        internal static string ConfirmMigrationCancel {
            get {
                return ResourceManager.GetString("ConfirmMigrationCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consistent Device Management.
        /// </summary>
        internal static string ConsistentDeviceManagement {
            get {
                return ResourceManager.GetString("ConsistentDeviceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curate Apps in the Google Play Store.
        /// </summary>
        internal static string CurateApps {
            get {
                return ResourceManager.GetString("CurateApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of {1} new devices are eligible for migration.
        /// </summary>
        internal static string DeviceCountEdit {
            get {
                return ResourceManager.GetString("DeviceCountEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of {1} devices are eligible for migration.
        /// </summary>
        internal static string DeviceCountStatistic {
            get {
                return ResourceManager.GetString("DeviceCountStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A notification will be sent to eligible devices in the selected Smart Groups informing employees about the migration and prompting them to take action to proceed. You can monitor their progress on the Legacy Android Migration page..
        /// </summary>
        internal static string DevicePreviewDescription {
            get {
                return ResourceManager.GetString("DevicePreviewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices Migrated.
        /// </summary>
        internal static string DevicesMigrated {
            get {
                return ResourceManager.GetString("DevicesMigrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices not being migrated are never affected..
        /// </summary>
        internal static string DevicesNotMigratedAreNeverEffected {
            get {
                return ResourceManager.GetString("DevicesNotMigratedAreNeverEffected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating your legacy Android administration to work managed or work profiles is easier than ever!.
        /// </summary>
        internal static string EasierLegacyAndroidMigration {
            get {
                return ResourceManager.GetString("EasierLegacyAndroidMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligibility Status.
        /// </summary>
        internal static string EligibilityStatus {
            get {
                return ResourceManager.GetString("EligibilityStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure every feature works the same across every OEM device..
        /// </summary>
        internal static string EveryFeatureWorks {
            get {
                return ResourceManager.GetString("EveryFeatureWorks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export details.
        /// </summary>
        internal static string ExprtMigrationDeviceDetail {
            get {
                return ResourceManager.GetString("ExprtMigrationDeviceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Get Started.
        /// </summary>
        internal static string HowToGetStartedLegacyAndroidMigration {
            get {
                return ResourceManager.GetString("HowToGetStartedLegacyAndroidMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase Employee Productivity.
        /// </summary>
        internal static string IncreaseProductivity {
            get {
                return ResourceManager.GetString("IncreaseProductivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiated Date.
        /// </summary>
        internal static string InitiatedDate {
            get {
                return ResourceManager.GetString("InitiatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Organization Group UUID format.
        /// </summary>
        internal static string InvalidOgUUIDFormat {
            get {
                return ResourceManager.GetString("InvalidOgUUIDFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to learn how.
        /// </summary>
        internal static string LearnHowToEnsureLink {
            get {
                return ResourceManager.GetString("LearnHowToEnsureLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your legacy administration remains intact until migration is complete..
        /// </summary>
        internal static string LegacyAdministrationRemainsIntact {
            get {
                return ResourceManager.GetString("LegacyAdministrationRemainsIntact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The devices listed below were on legacy administration when the Smart Groups above were selected. Any devices added to these Smart Groups in the future will appear as newly discovered devices. {0} to see breakdown of all devices that were migrated, including devices from Smart Groups that may have been removed..
        /// </summary>
        internal static string LegacyAndroidMigrationDeviceExport {
            get {
                return ResourceManager.GetString("LegacyAndroidMigrationDeviceExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating and monitoring your Legacy Android administration to work profiles just got easier!.
        /// </summary>
        internal static string LegacyAndroidMigrationGotEasier {
            get {
                return ResourceManager.GetString("LegacyAndroidMigrationGotEasier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Android Migration Help.
        /// </summary>
        internal static string LegacyAndroidMigrationHelpText {
            get {
                return ResourceManager.GetString("LegacyAndroidMigrationHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy Android Migration.
        /// </summary>
        internal static string LegacyAndroidMigrationTitle {
            get {
                return ResourceManager.GetString("LegacyAndroidMigrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate now to gain more control and consistency across all OEM devices with improved security and a better overall experience for employees with BYOD devices..
        /// </summary>
        internal static string LegacyAndroidMigrationWelcomeWindowDescription {
            get {
                return ResourceManager.GetString("LegacyAndroidMigrationWelcomeWindowDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock down work managed devices with Launcher and advanced device restrictions. Allow work apps and data to be stored separately for employee owned devices..
        /// </summary>
        internal static string LockDownAllowWorkApps {
            get {
                return ResourceManager.GetString("LockDownAllowWorkApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to public app.
        /// </summary>
        internal static string MakeSureLink {
            get {
                return ResourceManager.GetString("MakeSureLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure every public app is approved for your organization {0} and learn how to ensure employees have everything they need to stay productive {1}..
        /// </summary>
        internal static string MakeSureToApprovePublicApps {
            get {
                return ResourceManager.GetString("MakeSureToApprovePublicApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure every {0} is approved for your organization and {1} to ensure employees have everything they need to stay productive..
        /// </summary>
        internal static string MakeSureToApprovePublicAppsWorkManaged {
            get {
                return ResourceManager.GetString("MakeSureToApprovePublicAppsWorkManaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Public and Internal Apps.
        /// </summary>
        internal static string ManageBothApps {
            get {
                return ResourceManager.GetString("ManageBothApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate devices without performing a factory reset or reboot and ensure features work the same across every OEM device with ease..
        /// </summary>
        internal static string MigrateEveryFeature {
            get {
                return ResourceManager.GetString("MigrateEveryFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate with More Control and Consistency.
        /// </summary>
        internal static string MigrateMoreControl {
            get {
                return ResourceManager.GetString("MigrateMoreControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate with Confidence.
        /// </summary>
        internal static string MigrateWithConfidence {
            get {
                return ResourceManager.GetString("MigrateWithConfidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrating.
        /// </summary>
        internal static string Migrating {
            get {
                return ResourceManager.GetString("Migrating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All {0} legacy Android devices in the selected Smart Groups are eligible for migration..
        /// </summary>
        internal static string MigrationAllCompatible {
            get {
                return ResourceManager.GetString("MigrationAllCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Certificate.
        /// </summary>
        internal static string MigrationCertificate {
            get {
                return ResourceManager.GetString("MigrationCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully deleted..
        /// </summary>
        internal static string MigrationDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("MigrationDeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After employees have chosen to upgrade to Android Enterprise, this message will inform them about the migration and prompt them to take action to proceed.
        /// </summary>
        internal static string MigrationDescription {
            get {
                return ResourceManager.GetString("MigrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration can have a maximum of 10 SmartGroup Assignments.
        /// </summary>
        internal static string MigrationLimitReached {
            get {
                return ResourceManager.GetString("MigrationLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After employees have chosen to upgrade to Android Enterprise, this message will inform them about the migration and prompt them to take action to proceed..
        /// </summary>
        internal static string MigrationMessageDescription {
            get {
                return ResourceManager.GetString("MigrationMessageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to Android Enterprise now for easy and secure access to all your apps in one place. If you decide it’s not for you, you can turn this feature off at any time. Go to Settings &gt; Accounts &gt; Work Profile Settings.
        /// </summary>
        internal static string MigrationMessagePlaceholder {
            get {
                return ResourceManager.GetString("MigrationMessagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices in the selected Smart Groups are eligible for migration. Select Smart Groups that include legacy Android devices to proceed..
        /// </summary>
        internal static string MigrationNoDevicesCompatible {
            get {
                return ResourceManager.GetString("MigrationNoDevicesCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration not found..
        /// </summary>
        internal static string MigrationNotFound {
            get {
                return ResourceManager.GetString("MigrationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of {1} legacy Android devices in the selected Smart Groups are eligible for migration. Migration will be applied to only these devices if you proceed..
        /// </summary>
        internal static string MigrationSomeDevicesCompatible {
            get {
                return ResourceManager.GetString("MigrationSomeDevicesCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been successfully created..
        /// </summary>
        internal static string MigrationSuccessMessage {
            get {
                return ResourceManager.GetString("MigrationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep your personal and work lives separate, on one device.
        /// </summary>
        internal static string MigrationTitlePlaceholder {
            get {
                return ResourceManager.GetString("MigrationTitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration Type.
        /// </summary>
        internal static string MigrationType {
            get {
                return ResourceManager.GetString("MigrationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload a migration certificate.
        /// </summary>
        internal static string MissingCertificateError {
            get {
                return ResourceManager.GetString("MissingCertificateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitoring.
        /// </summary>
        internal static string MonitoringLegacyAndroidMigration {
            get {
                return ResourceManager.GetString("MonitoringLegacyAndroidMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Control and Consistency.
        /// </summary>
        internal static string MoreControlAndConstistency {
            get {
                return ResourceManager.GetString("MoreControlAndConstistency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Attention.
        /// </summary>
        internal static string NeedsAttention {
            get {
                return ResourceManager.GetString("NeedsAttention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Migration.
        /// </summary>
        internal static string NewLegacyAndroidMigration {
            get {
                return ResourceManager.GetString("NewLegacyAndroidMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Migration.
        /// </summary>
        internal static string NewMigrationTitle {
            get {
                return ResourceManager.GetString("NewMigrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices in the smart groups chosen are compatible for migration.  Please choose compatible devices before proceeding..
        /// </summary>
        internal static string NoDevicesError {
            get {
                return ResourceManager.GetString("NoDevicesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No eligible legacy Android devices found.
        /// </summary>
        internal static string NoEligibleDevices {
            get {
                return ResourceManager.GetString("NoEligibleDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new eligible legacy Android devices found.
        /// </summary>
        internal static string NoEligibleDevicesEdit {
            get {
                return ResourceManager.GetString("NoEligibleDevicesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Impact on Existing Devices.
        /// </summary>
        internal static string NoImpactOnExistingDevices {
            get {
                return ResourceManager.GetString("NoImpactOnExistingDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new eligible legacy Android device found in the selected Smart Groups..
        /// </summary>
        internal static string NoNewDevices {
            get {
                return ResourceManager.GetString("NoNewDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No organization group found for the given organization group UUID..
        /// </summary>
        internal static string NoOgFound {
            get {
                return ResourceManager.GetString("NoOgFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Compatible.
        /// </summary>
        internal static string NotCompatible {
            get {
                return ResourceManager.GetString("NotCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No need for complete device control since work apps and their data are stored and managed separately from personal apps..
        /// </summary>
        internal static string NotCompleteDeviceControl {
            get {
                return ResourceManager.GetString("NotCompleteDeviceControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing Command.
        /// </summary>
        internal static string PreparingCommand {
            get {
                return ResourceManager.GetString("PreparingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Requisites.
        /// </summary>
        internal static string Prerequisites {
            get {
                return ResourceManager.GetString("Prerequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you migrate, please ensure that you’ve completed the following required prerequisites to ensure migration goes through smoothly. Not completing them could either lead to failed migrations or users not being able to access all the apps they need..
        /// </summary>
        internal static string PrerequisitesDescription {
            get {
                return ResourceManager.GetString("PrerequisitesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide employees a more unified and reliable experience and allow public apps to install silently on any device. Work managed devices can also silently install internal apps..
        /// </summary>
        internal static string ProvideUnifiedAppExperience {
            get {
                return ResourceManager.GetString("ProvideUnifiedAppExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private app.
        /// </summary>
        internal static string PublishedAsAPrivateApp {
            get {
                return ResourceManager.GetString("PublishedAsAPrivateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish Internal Apps.
        /// </summary>
        internal static string PublishInternalApps {
            get {
                return ResourceManager.GetString("PublishInternalApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure every internal app is published as a private app in the Google Play store {0}. {1}.
        /// </summary>
        internal static string PublishInternalAppsInPlayStore {
            get {
                return ResourceManager.GetString("PublishInternalAppsInPlayStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure every internal app is published as a {0} in the Google Play store for work profile devices. Internal apps can be silently installed using Workspace ONE UEM for work managed devices. {1}.
        /// </summary>
        internal static string PublishInternalAppsInPlayStoreWorkManaged {
            get {
                return ResourceManager.GetString("PublishInternalAppsInPlayStoreWorkManaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After successful staged migrations, push your migration out to the rest of your organization..
        /// </summary>
        internal static string PushMigrationOut {
            get {
                return ResourceManager.GetString("PushMigrationOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to legacy profiles.
        /// </summary>
        internal static string RecreateLegacyProfiles {
            get {
                return ResourceManager.GetString("RecreateLegacyProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreate {0} as new profiles and easily recreate {1} with legacy profiles for work managed devices before you migrate..
        /// </summary>
        internal static string RecreateLegacyProfilesProductsToNew {
            get {
                return ResourceManager.GetString("RecreateLegacyProfilesProductsToNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreate legacy profiles as new profiles before migration {0}..
        /// </summary>
        internal static string RecreateLegacyProfilesToNew {
            get {
                return ResourceManager.GetString("RecreateLegacyProfilesToNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to products.
        /// </summary>
        internal static string RecreateProducts {
            get {
                return ResourceManager.GetString("RecreateProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreate Profiles.
        /// </summary>
        internal static string RecreateProfiles {
            get {
                return ResourceManager.GetString("RecreateProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreate Profiles and Products.
        /// </summary>
        internal static string RecreateProfilesAndProducts {
            get {
                return ResourceManager.GetString("RecreateProfilesAndProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Migration Certificate.
        /// </summary>
        internal static string RetrieveMigrationCertificate {
            get {
                return ResourceManager.GetString("RetrieveMigrationCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A certificate is required to ensure the integrity of the migration. Contact your Zebra representative to generate a certificate for your company..
        /// </summary>
        internal static string RetrieveMigrationCertificateDescription {
            get {
                return ResourceManager.GetString("RetrieveMigrationCertificateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A notification will be sent to selected devices about the migration and prompting them to take action to proceed..
        /// </summary>
        internal static string RetryMigrationSuccess {
            get {
                return ResourceManager.GetString("RetryMigrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See which devices are complete, in progress, and assigned..
        /// </summary>
        internal static string SeeDevicesCompleteInprogressAssigned {
            get {
                return ResourceManager.GetString("SeeDevicesCompleteInprogressAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Smart Groups you want to migrate..
        /// </summary>
        internal static string SelectMigrationSmartGroups {
            get {
                return ResourceManager.GetString("SelectMigrationSmartGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Migration Type.
        /// </summary>
        internal static string SelectMigrationType {
            get {
                return ResourceManager.GetString("SelectMigrationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Work and Personal Apps Separate and Secure.
        /// </summary>
        internal static string SeparateWorkAndPersonalApps {
            get {
                return ResourceManager.GetString("SeparateWorkAndPersonalApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration and monitoring is made simple with the tools you need to maximize control and consistency..
        /// </summary>
        internal static string SetUpLegacyAndroidMigration {
            get {
                return ResourceManager.GetString("SetUpLegacyAndroidMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SmartGroup not found or user does not have access to it.
        /// </summary>
        internal static string SmartGroupInAccessible {
            get {
                return ResourceManager.GetString("SmartGroupInAccessible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0} More.
        /// </summary>
        internal static string SmartGroupMore {
            get {
                return ResourceManager.GetString("SmartGroupMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test a few devices to ensure employees&apos; devices have successfully migrated..
        /// </summary>
        internal static string TestFewDevices {
            get {
                return ResourceManager.GetString("TestFewDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing.
        /// </summary>
        internal static string TestingLegacyAndroidMigration {
            get {
                return ResourceManager.GetString("TestingLegacyAndroidMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track devices&apos; progress and migration health before pushing organization-wide..
        /// </summary>
        internal static string TrackDeviceProgressLegacyAndroidMigration {
            get {
                return ResourceManager.GetString("TrackDeviceProgressLegacyAndroidMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Progress and Take Action.
        /// </summary>
        internal static string TrackProgressAndTakeAction {
            get {
                return ResourceManager.GetString("TrackProgressAndTakeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} devices will be removed based on the current Smart Group selection..
        /// </summary>
        internal static string UnassignedDevices {
            get {
                return ResourceManager.GetString("UnassignedDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide employees with a unified and more reliable app experience..
        /// </summary>
        internal static string UnifiedAppExperience {
            get {
                return ResourceManager.GetString("UnifiedAppExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select migration certificate to upload.
        /// </summary>
        internal static string UploadCertificateHelpText {
            get {
                return ResourceManager.GetString("UploadCertificateHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to androidWorkUserEmail field cannot be null or empty.
        /// </summary>
        internal static string UserEmailCannotBeNullOrWhitespace {
            get {
                return ResourceManager.GetString("UserEmailCannotBeNullOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to androidWorkUserPassword field cannot be null or empty.
        /// </summary>
        internal static string UserPasswordCannotBeNullOrWhitepsace {
            get {
                return ResourceManager.GetString("UserPasswordCannotBeNullOrWhitepsace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate.
        /// </summary>
        internal static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validates whether or not legacy Android devices within the selected Smart Groups exist.
        /// </summary>
        internal static string ValidateTooltip {
            get {
                return ResourceManager.GetString("ValidateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Network Settings.
        /// </summary>
        internal static string VerifyNetworkSettings {
            get {
                return ResourceManager.GetString("VerifyNetworkSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting On User.
        /// </summary>
        internal static string WaitingOnUser {
            get {
                return ResourceManager.GetString("WaitingOnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is this migration for?.
        /// </summary>
        internal static string WhatIsMigrationFor {
            get {
                return ResourceManager.GetString("WhatIsMigrationFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What to Expect.
        /// </summary>
        internal static string WhatToExpect {
            get {
                return ResourceManager.GetString("WhatToExpect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate corporate owned devices from device administrator to work managed. Requires Zebra devices running Android 7 and higher..
        /// </summary>
        internal static string WorkManagedMigrationDescription {
            get {
                return ResourceManager.GetString("WorkManagedMigrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrate personally owned devices from device administrator to work profile..
        /// </summary>
        internal static string WorkProfileMigrationDescription {
            get {
                return ResourceManager.GetString("WorkProfileMigrationDescription", resourceCulture);
            }
        }
    }
}
