//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WanderingWiFi.AirWatch.Globalization.Resources.Express {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LabelValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WanderingWiFi.AirWatch.Globalization.Resources.Express.LabelValues", typeof(LabelValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve and Publish Public Apps.
        /// </summary>
        internal static string ApproveAndPublishPublicApps {
            get {
                return ResourceManager.GetString("ApproveAndPublishPublicApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-add any public app from your existing Blueprints that you published prior to registering with Android EMM to approve and publish them to both your legacy and Android Enterprise devices..
        /// </summary>
        internal static string ApproveAndPublishPublicAppsDescription {
            get {
                return ResourceManager.GetString("ApproveAndPublishPublicAppsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} devices will be removed based on the current group selection..
        /// </summary>
        internal static string ArgDevicesRemovedBasedOnGroupSelection {
            get {
                return ResourceManager.GetString("ArgDevicesRemovedBasedOnGroupSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} out of {1} legacy Android devices in the selected groups are eligible for migration. Migration will be applied to only these devices if you proceed..
        /// </summary>
        internal static string ArgOutOfArgLegacyAndroidMigrationNotification {
            get {
                return ResourceManager.GetString("ArgOutOfArgLegacyAndroidMigrationNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collect Device Location Data.
        /// </summary>
        internal static string CollectDeviceLocationData {
            get {
                return ResourceManager.GetString("CollectDeviceLocationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices in Blueprint {0}.
        /// </summary>
        internal static string DevicesInBlueprintArg {
            get {
                return ResourceManager.GetString("DevicesInBlueprintArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only devices of users that have been assigned to Blueprints can be selected at this time. You can also choose to migrate all your devices at once by selecting &apos;All Devices&apos;..
        /// </summary>
        internal static string DevicesSelectionTooltipText {
            get {
                return ResourceManager.GetString("DevicesSelectionTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute App Catalog to devices.
        /// </summary>
        internal static string DistributeAppCatalogToDevices {
            get {
                return ResourceManager.GetString("DistributeAppCatalogToDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The devices listed below were on legacy administration when the groups above were selected. Any devices added to these groups in the future will appear as newly discovered devices. {0} to see breakdown of all devices that were migrated, including devices from groups that may have been removed..
        /// </summary>
        internal static string ExpressLegacyAndroidMigrationDeviceExportArg {
            get {
                return ResourceManager.GetString("ExpressLegacyAndroidMigrationDeviceExportArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All {0} legacy Android devices in the selected groups are eligible for migration..
        /// </summary>
        internal static string ExpressMigrationAllCompatible {
            get {
                return ResourceManager.GetString("ExpressMigrationAllCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration can have a maximum of 10 group assignments..
        /// </summary>
        internal static string ExpressMigrationLimitReached {
            get {
                return ResourceManager.GetString("ExpressMigrationLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices in the selected groups are eligible for migration. Select groups that include legacy Android devices to proceed..
        /// </summary>
        internal static string ExpressMigrationNoDevicesCompatible {
            get {
                return ResourceManager.GetString("ExpressMigrationNoDevicesCompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new eligible legacy Android device found in the selected groups..
        /// </summary>
        internal static string ExpressNoNewDevices {
            get {
                return ResourceManager.GetString("ExpressNoNewDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything you need to secure and manage your company&apos;s mobile devices is here. You can:.
        /// </summary>
        internal static string ExpressWelcomeMessageHeader {
            get {
                return ResourceManager.GetString("ExpressWelcomeMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will your employees be using Android devices?.
        /// </summary>
        internal static string IsAfwRequired {
            get {
                return ResourceManager.GetString("IsAfwRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user group found with that name..
        /// </summary>
        internal static string NoGroupFound {
            get {
                return ResourceManager.GetString("NoGroupFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A notification will be sent to eligible devices in the selected groups informing employees about the migration and prompting them to take action to proceed. You can monitor their progress on the Legacy Android Migration page..
        /// </summary>
        internal static string NotificationDevicePreviewAndroidLegacyMigration {
            get {
                return ResourceManager.GetString("NotificationDevicePreviewAndroidLegacyMigration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user found with that name..
        /// </summary>
        internal static string NoUserFound {
            get {
                return ResourceManager.GetString("NoUserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s answer a few simple questions to help you set up:.
        /// </summary>
        internal static string QuestionnaireDescription {
            get {
                return ResourceManager.GetString("QuestionnaireDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-save your Policies.
        /// </summary>
        internal static string ResaveYourPolicies {
            get {
                return ResourceManager.GetString("ResaveYourPolicies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit and re-save the Policies section of any existing Blueprints that you published prior to registering with Android EMM..
        /// </summary>
        internal static string ResaveYourPoliciesDescription {
            get {
                return ResourceManager.GetString("ResaveYourPoliciesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-save your Resources.
        /// </summary>
        internal static string ResaveYourResources {
            get {
                return ResourceManager.GetString("ResaveYourResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit and re-save any Email and Wi-Fi resources you configured in existing Blueprints that you published prior to registering with Android EMM..
        /// </summary>
        internal static string ResaveYourResourcesDescription {
            get {
                return ResourceManager.GetString("ResaveYourResourcesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search current groups.
        /// </summary>
        internal static string SearchCurrentGroups {
            get {
                return ResourceManager.GetString("SearchCurrentGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search current users.
        /// </summary>
        internal static string SearchCurrentUsers {
            get {
                return ResourceManager.GetString("SearchCurrentUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the devices you want to migrate..
        /// </summary>
        internal static string SelectMigrationDevices {
            get {
                return ResourceManager.GetString("SelectMigrationDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start typing to add Groups.
        /// </summary>
        internal static string StartTypingToAddGroups {
            get {
                return ResourceManager.GetString("StartTypingToAddGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to collect device location data?.
        /// </summary>
        internal static string WantToCollectDeviceLocationData {
            get {
                return ResourceManager.GetString("WantToCollectDeviceLocationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to distribute an app catalog to your devices?.
        /// </summary>
        internal static string WantToDistributeAppCatalogToDevices {
            get {
                return ResourceManager.GetString("WantToDistributeAppCatalogToDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sure. You can return to this survey from the Getting Started menu at any time if you want to change your answer..
        /// </summary>
        internal static string WarningForNotCollectingLocationData {
            get {
                return ResourceManager.GetString("WarningForNotCollectingLocationData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That&apos;s ok. If you change your mind, Active Directory can be set up later from the Settings menu..
        /// </summary>
        internal static string WarningForNotConfiguringAd {
            get {
                return ResourceManager.GetString("WarningForNotConfiguringAd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you plan on enrolling Android devices in the future, you can always set up your Android EMM registration from the Setting menu later..
        /// </summary>
        internal static string WarningForNotConfiguringAfw {
            get {
                return ResourceManager.GetString("WarningForNotConfiguringAfw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you plan on enrolling Apple devices in the future, you can always set up your APNs certificate from the Settings menu later..
        /// </summary>
        internal static string WarningForNotConfiguringApns {
            get {
                return ResourceManager.GetString("WarningForNotConfiguringApns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alright. You can always go to the Settings menu if you decide to set up your Apple VPP account later..
        /// </summary>
        internal static string WarningForNotConfiguringVpp {
            get {
                return ResourceManager.GetString("WarningForNotConfiguringVpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it. If you want to change your answer you can return to this survery from the Getting Started menu at any time..
        /// </summary>
        internal static string WarningForNotDistributingAppCatalog {
            get {
                return ResourceManager.GetString("WarningForNotDistributingAppCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace ONE Express.
        /// </summary>
        internal static string WorkspaceOneExpress {
            get {
                return ResourceManager.GetString("WorkspaceOneExpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure to start enrolling, securing and managing devices and providing corporate resources to employees..
        /// </summary>
        internal static string WorkspaceOneExpressSetupTrackInfo {
            get {
                return ResourceManager.GetString("WorkspaceOneExpressSetupTrackInfo", resourceCulture);
            }
        }
    }
}
