test: &default

  # # product Name
  product_name: test

  # # bundle version
  version: 4.8.1

  # # Singleton server
  vip_server:

  # # translation bundle Path
  translation_bundle: ./config/locales/l10n/bundles

  # # source bundle Path
  source_bundle: ./config/locales/default

  # # memory cache's expration(minutes), default value is 24*60
  cache_expiry_period: 36

  # # the path to log file, default target is STDOUT
  log_file: ./unit_test.log

  # # the lowest level to be logged, default value is INFO
  log_level: DEBUG

  # # tag for pseudo translation, default value is '@@'
  pseudo_tag: "@@"

development:
  <<: *default

production:
  <<: *default
  log_level: INFO
