version: '2.1'
orbs:
  go: circleci/go@1.7.0
jobs:
  checkheader:
    executor:
      name: go/default
      tag: '1.16'
    steps:
      - checkout
      # - go/load-cache
      # - go/mod-download
      # - go/save-cache
      - run:
          name: check header
          env: TEST=check_header
          command: |
            git clone --branch=devops https://github.com/vmware/singleton.git devops
            cp devops/check_headers.py .
            chmod +x check_headers.py
            python3 ./check_headers.py
            


  build:
    executor:
        name: go/default
        tag: '1.16'
    steps:
    - checkout
    - run:
        name: build
#        env: TEST=build
        command: |
          ls -ltr
          make build
          ls -ltr
          ls -ltr builds

#          if [ x${TEST} = xbuild ]; then
          
#          fi


workflows:
  main:
    jobs:
      - checkheader:
          filters:
            branches:
              only:
                - g11n-go-service
      - build:
          filters:
            branches:
              only:
                - g11n-go-service

          