// Code generated by go-bindata. DO NOT EDIT.
// sources:
// other/info.yaml
// other/localemap.json
package otherbindata

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data, name string) ([]byte, error) {
	gz, err := gzip.NewReader(strings.NewReader(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _otherInfoYaml = "\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\x4c\xc9\x31\x0e\xc2\x30\x0c\x05\xd0\xdd\xa7\xc8\x05\x7a\x01\x8f\x88\x85\x01\x46\x76\xb7\xf9\x4a\x23\xb5\xb6\xe4\x38\x25\xdc\x9e\x21\x0b\xe3\xd3\x53\x39\xc1\xa9\x55\x2d\x07\xc2\x74\x29\xb6\x34\xf8\x05\x27\xe9\xb1\x9b\x73\x7a\x3f\x3f\xe2\xa0\x0b\xde\xaa\x29\xa7\x31\x06\x6d\x0e\x09\xe4\xdb\x77\x72\xed\xf5\xc8\x77\x09\xfc\xf1\xd5\xcf\x15\xce\xb4\xed\xa2\x05\x8f\x3c\xeb\x17\x00\x00\xff\xff\x8c\x27\xf8\x7d\x6f\x00\x00\x00"

func otherInfoYamlBytes() ([]byte, error) {
	return bindataRead(
		_otherInfoYaml,
		"other/info.yaml",
	)
}

func otherInfoYaml() (*asset, error) {
	bytes, err := otherInfoYamlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "other/info.yaml", size: 111, mode: os.FileMode(420), modTime: time.Unix(1692771662, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _otherLocalemapJson = "\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\xff\xaa\xe6\x52\x50\x50\xaa\xca\xd0\x4d\xce\x53\xb2\x02\x33\x3c\x12\xf3\x8a\x95\x74\xa0\xa2\x25\xe5\x08\xd1\x12\xb8\x68\x46\x62\x5e\x31\x0e\x0d\x19\x89\x79\x25\x68\xba\xb8\x6a\x01\x01\x00\x00\xff\xff\xb1\xf2\x73\x2d\x64\x00\x00\x00"

func otherLocalemapJsonBytes() ([]byte, error) {
	return bindataRead(
		_otherLocalemapJson,
		"other/localemap.json",
	)
}

func otherLocalemapJson() (*asset, error) {
	bytes, err := otherLocalemapJsonBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "other/localemap.json", size: 100, mode: os.FileMode(420), modTime: time.Unix(1685851043, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"other/info.yaml": otherInfoYaml,
	"other/localemap.json": otherLocalemapJson,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"other": &bintree{nil, map[string]*bintree{
		"info.yaml": &bintree{otherInfoYaml, map[string]*bintree{}},
		"localemap.json": &bintree{otherLocalemapJson, map[string]*bintree{}},
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

