source "https://rubygems.org"

group :test do
    gem 'rspec'
    gem 'rest-client'
    gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
    gem 'singleton-client-test', '0.7.0.29'
    #gem "singleton-ruby", :path => "../../../../ruby_client/singleton"
    # e/Singleton_client_test/Ruby/client/1.5/singleton
    gem 'request_store'
  end