HttpCollections:
    -   name: "API_V1"
        file: "VMCUI_v1.json"
        thread_number: 1
        loop_count: 50
        thread_group_name: "API_V1"
        threshold_limit: 0.96

    -   name: "API_V2"
        file: "VMCUI_v2.json"
        thread_number: 1
        loop_count: 50
        thread_group_name: "API_V2"
        threshold_limit: 0.96