//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestSingleton.testdata {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UnitTestSingleton.testdata.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;code&quot;:200,&quot;message&quot;:&quot;OK&quot;,&quot;serverTime&quot;:&quot;&quot;},&quot;signature&quot;:&quot;&quot;,&quot;data&quot;:{&quot;productName&quot;:&quot;CSHARP&quot;,&quot;version&quot;:&quot;1.0.0&quot;,&quot;dataOrigin&quot;:&quot;bundle&quot;,&quot;pseudo&quot;:false,&quot;machineTranslation&quot;:false,&quot;component&quot;:&quot;about&quot;,&quot;messages&quot;:{&quot;about.message&quot;:&quot;Ihrer Bewerbungs Beschreibung Seite.&quot;,&quot;about.title&quot;:&quot;Über&quot;,&quot;about.description&quot;:&quot;Nutzen Sie diesen Bereich, um zusätzliche Informationen zu liefern&quot;},&quot;locale&quot;:&quot;de&quot;,&quot;status&quot;:&quot;&quot;,&quot;id&quot;:0}}.
        /// </summary>
        internal static string get_component_about_de {
            get {
                return ResourceManager.GetString("get_component_about_de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;code&quot;:200,&quot;message&quot;:&quot;OK&quot;,&quot;serverTime&quot;:&quot;&quot;},&quot;signature&quot;:&quot;&quot;,&quot;data&quot;:{&quot;productName&quot;:&quot;CSHARP&quot;,&quot;version&quot;:&quot;1.0.0&quot;,&quot;dataOrigin&quot;:&quot;bundle&quot;,&quot;pseudo&quot;:false,&quot;machineTranslation&quot;:false,&quot;component&quot;:&quot;about&quot;,&quot;messages&quot;:{&quot;about.message&quot;:&quot;Your application description page.&quot;,&quot;about.title&quot;:&quot;About&quot;,&quot;about.description&quot;:&quot;Use this area to provide additional information&quot;},&quot;locale&quot;:&quot;en&quot;,&quot;status&quot;:&quot;&quot;,&quot;id&quot;:0}}
        ///.
        /// </summary>
        internal static string get_component_about_en {
            get {
                return ResourceManager.GetString("get_component_about_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;code&quot;:200,&quot;message&quot;:&quot;OK&quot;,&quot;serverTime&quot;:&quot;&quot;},&quot;signature&quot;:&quot;&quot;,&quot;data&quot;:{&quot;productName&quot;:&quot;CSHARP&quot;,&quot;version&quot;:&quot;1.0.0&quot;,&quot;dataOrigin&quot;:&quot;bundle&quot;,&quot;pseudo&quot;:false,&quot;machineTranslation&quot;:false,&quot;component&quot;:&quot;about&quot;,&quot;messages&quot;:{&quot;about.message&quot;:&quot;应用程序说明页。&quot;,&quot;about.title&quot;:&quot;关于&quot;,&quot;about.description&quot;:&quot;使用此区域可提供其他信息&quot;},&quot;locale&quot;:&quot;zh-Hans&quot;,&quot;status&quot;:&quot;&quot;,&quot;id&quot;:0}}.
        /// </summary>
        internal static string get_component_about_zh_Hans {
            get {
                return ResourceManager.GetString("get_component_about_zh-Hans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;code&quot;:200,&quot;message&quot;:&quot;OK&quot;,&quot;serverTime&quot;:&quot;&quot;},&quot;signature&quot;:&quot;&quot;,&quot;data&quot;:{&quot;components&quot;:[&quot;about&quot;,&quot;contact&quot;,&quot;index&quot;,&quot;common&quot;],&quot;version&quot;:&quot;1.0.0&quot;,&quot;productName&quot;:&quot;CSHARP&quot;}}.
        /// </summary>
        internal static string get_componentlist {
            get {
                return ResourceManager.GetString("get_componentlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;code&quot;:200,&quot;message&quot;:&quot;OK&quot;,&quot;serverTime&quot;:&quot;&quot;},&quot;signature&quot;:&quot;&quot;,&quot;data&quot;:{&quot;locales&quot;:[&quot;zh-Hans&quot;,&quot;zh-Hant&quot;,&quot;fr&quot;,&quot;en&quot;,&quot;ja&quot;,&quot;ko&quot;,&quot;de&quot;],&quot;version&quot;:&quot;1.0.0&quot;,&quot;productName&quot;:&quot;CSHARP&quot;}}.
        /// </summary>
        internal static string get_localelist {
            get {
                return ResourceManager.GetString("get_localelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://127.0.0.1:8090/i18n/api/v2/translation/products/CSHARP/versions/1.0.0/locales/en/components/about?pseudo=false&amp;machineTranslation=false&amp;checkTranslationStatus=false.
        /// </summary>
        internal static string get_url_3 {
            get {
                return ResourceManager.GetString("get_url_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://127.0.0.1:8090/i18n/api/v2/translation/products/CSHARP/versions/1.0.0/locales/de/components/about?pseudo=false&amp;machineTranslation=false&amp;checkTranslationStatus=false
        ///.
        /// </summary>
        internal static string get_url_4 {
            get {
                return ResourceManager.GetString("get_url_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://127.0.0.1:8090/i18n/api/v2/translation/products/CSHARP/versions/1.0.0/locales/zh-Hans/components/about?pseudo=false&amp;machineTranslation=false&amp;checkTranslationStatus=false
        ///.
        /// </summary>
        internal static string get_url_5 {
            get {
                return ResourceManager.GetString("get_url_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to get_url_1 = http://127.0.0.1:8090/i18n/api/v2/translation/products/CSHARP/versions/1.0.0/localelist
        ///get_response_1 = (res)get_localelist
        ///
        ///get_url_2 = http://127.0.0.1:8090/i18n/api/v2/translation/products/CSHARP/versions/1.0.0/componentlist
        ///get_response_2 = (res)get_componentlist
        ///
        ///get_url_3 = (res)get_url_3
        ///get_response_3 = (res)get_component_about_en
        ///
        ///get_url_4 = (res)get_url_4
        ///get_response_4 = (res)get_component_about_de
        ///
        ///get_url_5 = (res)get_url_5
        ///get_response_5 = (res)get_component_about_zh [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string http_list {
            get {
                return ResourceManager.GetString("http_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;response&quot;:{&quot;code&quot;:200,&quot;message&quot;:&quot;OK&quot;,&quot;serverTime&quot;:&quot;&quot;},&quot;signature&quot;:&quot;&quot;,&quot;data&quot;:{&quot;productName&quot;:&quot;CSHARP&quot;,&quot;version&quot;:&quot;1.0.0&quot;,&quot;dataOrigin&quot;:&quot;&quot;,&quot;pseudo&quot;:false,&quot;machineTranslation&quot;:false,&quot;source&quot;:&quot;&quot;,&quot;translation&quot;:&quot;Your application description page.&quot;,&quot;locale&quot;:&quot;en&quot;,&quot;key&quot;:&quot;about.message&quot;,&quot;component&quot;:&quot;about&quot;,&quot;status&quot;:&quot;The {0} and returned, English is not equal to recieved source.&quot;}}.
        /// </summary>
        internal static string post_collect_source {
            get {
                return ResourceManager.GetString("post_collect_source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://127.0.0.1:8090/i18n/api/v2/translation/products/CSHARP/versions/1.0.0/locales/en-US/components/about/keys/about.message?collectSource=true&amp;pseudo=false&amp;machineTranslation=false&amp;checkTranslationStatus=false
        ///.
        /// </summary>
        internal static string post_url_1 {
            get {
                return ResourceManager.GetString("post_url_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] TestSource {
            get {
                object obj = ResourceManager.GetObject("TestSource", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
