source "https://rubygems.org"

#gem 'singleton-ruby', '~> 0.2.1', :path => '/opt/git/github/linr211/rb-app/ruby-app/singleton-ruby'
gem 'singleton-ruby', '~> 0.2.1'

gem 'rest-client', '~> 2.0'

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
gem 'coderay'
gem 'sinatra'
gem 'haml'