source "https://rubygems.org"

#gem 'singleton-ruby', '~> 0.1.0', :path => '/opt/git/github/linr211/rb-app/ruby-app/singleton-ruby'
gem 'singleton-ruby', '~> 0.1.5'
gem 'singleton-cldr-rb', '0.0.6'
#gem 'singleton-cldr-rb', '0.0.5', :path => '/opt/git/github/linr211/rb-app/ruby-app/singleton-cldr-rb'

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
gem 'coderay'
gem 'sinatra'
gem 'haml'