BundleLocation: local # local or s3

LocalBundle:
  BasePath:  /Library/Tomcat/l10n/bundles

S3Bundle:
  PublicKeyFile: ### file content is used to decode AccessKey and SecretKey
  AccessKey: ###
  SecretKey: ###
  Region: ###
  BucketName: ###
  BundleRoot: ###

RefreshBundleInterval: 0s # interval to refresh bundle information

HeaderOfTraceID: # comma separated headers carrying trace ID

Server:
  RunMode: release # debug or release
  Schema: http   # http, https, http&https
  HTTPSPort: 8092
  HTTPPort: 8093
  ReadTimeout: 0s
  WriteTimeout: 0s
  CertFile: ###
  KeyFile: ###
  MaxHeaderBytes: 1024000
  CacheControl: max-age=30, public
  CompressionAlgorithm:  #gzip, br, gzip&br

CrossDomain:
  Enable: true
  AllowCredentials: true
  AllowOrigin: "*"
  AllowMethods: GET,POST,PUT,DELETE,OPTIONS
  AllowHeaders: csp-auth-token,Content-Type,x-xmp-ui,Authorization
  MaxAge: 3600s

LOG:
  Filename:
  MaxSize: 50 # megabytes
  MaxBackups: 20
  MaxAge: 365 # days
  FileLevel: debug
  Level: info

Cache:
  Enable: true
  MaxCost: 1000 # number of entities to store
  BufferItems: 64
  Expiration: 60s #seconds

SwaggerUI: true
