##
#Copyright 2019-2022 VMware, Inc.
#SPDX-License-Identifier: EPL-2.0
##
spring:
  profiles:
     active: db_dev
  application:
    name: vip-data-initdb
logging:
  config: classpath:log4j2-spring.xml
