
source "https://rubygems.org"

#if File.exists? "../singleton-ruby.gemspec"
#  gem 'paypal-sdk-core', :git => "https://github.com/singleton/singleton-ruby.git"
#  gem 'singleton-ruby', :path => ".."
#else
  #gem 'singleton-ruby'
#end

#gem 'singleton-ruby', '~> 0.1.0', :path => '/opt/git/github/linr211/rb-app/ruby-app/singleton-ruby'
gem 'singleton-ruby', '~> 0.1.0'

#gem 'singleton-cldr-rb', '~> 0.0.0', :path => '/opt/git/github/linr211/rb-app/ruby-app/singleton-cldr-rb'
gem 'singleton-cldr-rb', '0.0.2'

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]

gem 'coderay'
gem 'sinatra'
gem 'haml'
