//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WanderingWiFi.AirWatch.Globalization.Resources.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LabelValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WanderingWiFi.AirWatch.Globalization.Resources.Common.LabelValues", typeof(LabelValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API body contains characters that are restricted under Xss validation..
        /// </summary>
        internal static string AntiXssErrorMessage {
            get {
                return ResourceManager.GetString("AntiXssErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} account dropdown menu.
        /// </summary>
        internal static string ArgAccountDropDownMenu {
            get {
                return ResourceManager.GetString("ArgAccountDropDownMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} characters.
        /// </summary>
        internal static string ArgCharacters {
            get {
                return ResourceManager.GetString("ArgCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to {0} slide.
        /// </summary>
        internal static string ArgGoToPrevOrNextSlide {
            get {
                return ResourceManager.GetString("ArgGoToPrevOrNextSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to slide {0}.
        /// </summary>
        internal static string ArgGoToSpecificSlide {
            get {
                return ResourceManager.GetString("ArgGoToSpecificSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Opens Dialog.
        /// </summary>
        internal static string ArgOpensDialog {
            get {
                return ResourceManager.GetString("ArgOpensDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Platform.
        /// </summary>
        internal static string ArgPlatformLabel {
            get {
                return ResourceManager.GetString("ArgPlatformLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication App Token Notification.
        /// </summary>
        internal static string AuthenticationAppTokenNotification {
            get {
                return ResourceManager.GetString("AuthenticationAppTokenNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If the CSV template is being edited using the Microsoft Excel utility, make sure that the column format is set to &quot;Text&quot; to avoid loss of information due to format conversion..
        /// </summary>
        internal static string BatchImportCsvTemplateColumnFormatInfo {
            get {
                return ResourceManager.GetString("BatchImportCsvTemplateColumnFormatInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Dialog.
        /// </summary>
        internal static string CloseDialog {
            get {
                return ResourceManager.GetString("CloseDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Logo routes to corporate website.
        /// </summary>
        internal static string CompanyLogoWithUrl {
            get {
                return ResourceManager.GetString("CompanyLogoWithUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        internal static string CSV {
            get {
                return ResourceManager.GetString("CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current organization group is {0}.
        /// </summary>
        internal static string CurrentOrgLevelArg {
            get {
                return ResourceManager.GetString("CurrentOrgLevelArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the services required to run Custom Reports is missing. Please contact your Administrator..
        /// </summary>
        internal static string CustomIngestionServiceIsMissing {
            get {
                return ResourceManager.GetString("CustomIngestionServiceIsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data in row is not valid.
        /// </summary>
        internal static string DataInRowInvalid {
            get {
                return ResourceManager.GetString("DataInRowInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dell Command Update Error.
        /// </summary>
        internal static string DCUApplicationError {
            get {
                return ResourceManager.GetString("DCUApplicationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device BIOS Verification Failed.
        /// </summary>
        internal static string DeviceBiosVerificationFailed {
            get {
                return ResourceManager.GetString("DeviceBiosVerificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device BIOS Verification Unknown.
        /// </summary>
        internal static string DeviceBiosVerificationUnknown {
            get {
                return ResourceManager.GetString("DeviceBiosVerificationUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss All.
        /// </summary>
        internal static string DismissAll {
            get {
                return ResourceManager.GetString("DismissAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All notifications will be dismissed. Are you sure you want to continue?.
        /// </summary>
        internal static string DismissAllNotificationsConfirmation {
            get {
                return ResourceManager.GetString("DismissAllNotificationsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This door is locked.
        /// </summary>
        internal static string DoorIsLocked {
            get {
                return ResourceManager.GetString("DoorIsLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload cancelled, as we have identified this as a duplicate request. If the issue persists, please contact the administrator..
        /// </summary>
        internal static string DuplicateRequest {
            get {
                return ResourceManager.GetString("DuplicateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enforce Manifest.
        /// </summary>
        internal static string EnforceManifest {
            get {
                return ResourceManager.GetString("EnforceManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manifest will be reapplied on next check-in even if removed by end user..
        /// </summary>
        internal static string EnforceManifestToolTip {
            get {
                return ResourceManager.GetString("EnforceManifestToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a positive integer value..
        /// </summary>
        internal static string EnterPositiveIntegerValue {
            get {
                return ResourceManager.GetString("EnterPositiveIntegerValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while posting tenant binding details to Intelligence. Please contact Administrator..
        /// </summary>
        internal static string ErrorOccuredWhilePostingBindingDetailsToIntelligence {
            get {
                return ResourceManager.GetString("ErrorOccuredWhilePostingBindingDetailsToIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports.
        /// </summary>
        internal static string Exports {
            get {
                return ResourceManager.GetString("Exports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External OAuth Integration.
        /// </summary>
        internal static string ExternalOAuthIntegration {
            get {
                return ResourceManager.GetString("ExternalOAuthIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission to provision external OAuth client in UEM for auth purpose..
        /// </summary>
        internal static string ExternalOAuthIntegrationHelp {
            get {
                return ResourceManager.GetString("ExternalOAuthIntegrationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Service Integration.
        /// </summary>
        internal static string ExternalServiceIntegration {
            get {
                return ResourceManager.GetString("ExternalServiceIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission to provision any VMware external service like WS1 intelligence in UEM..
        /// </summary>
        internal static string ExternalServiceIntegrationHelp {
            get {
                return ResourceManager.GetString("ExternalServiceIntegrationHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Search.
        /// </summary>
        internal static string GlobalSearch {
            get {
                return ResourceManager.GetString("GlobalSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-08:00) Pacific Time (US &amp; Canada).
        /// </summary>
        internal static string GmtMinusEightTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtMinusEightTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-08:00) Baja California.
        /// </summary>
        internal static string GmtMinusEightTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtMinusEightTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-11:00) American Samoa, Niue.
        /// </summary>
        internal static string GmtMinusElevenTimeZone {
            get {
                return ResourceManager.GetString("GmtMinusElevenTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-05:00) Eastern Time (US &amp; Canada).
        /// </summary>
        internal static string GmtMinusFiveTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtMinusFiveTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-05:00) Bogota, Lima, Quito, Rio Branco.
        /// </summary>
        internal static string GmtMinusFiveTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtMinusFiveTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-05:00) Cayman Islands, Jamaica, Panama.
        /// </summary>
        internal static string GmtMinusFiveTimeZoneThird {
            get {
                return ResourceManager.GetString("GmtMinusFiveTimeZoneThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-04:00) Caracas.
        /// </summary>
        internal static string GmtMinusFourAndHalfTimeZoneFifth {
            get {
                return ResourceManager.GetString("GmtMinusFourAndHalfTimeZoneFifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-04:00) Santiago.
        /// </summary>
        internal static string GmtMinusFourTimeZoneFifth {
            get {
                return ResourceManager.GetString("GmtMinusFourTimeZoneFifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-04:00) Atlantic Time (Canada).
        /// </summary>
        internal static string GmtMinusFourTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtMinusFourTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-04:00) Georgetown, La Paz, Manaus, San Juan.
        /// </summary>
        internal static string GmtMinusFourTimeZoneFourth {
            get {
                return ResourceManager.GetString("GmtMinusFourTimeZoneFourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-04:00) Atlantic Time (Bermuda).
        /// </summary>
        internal static string GmtMinusFourTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtMinusFourTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-04:00) Asuncion.
        /// </summary>
        internal static string GmtMinusFourTimeZoneSixth {
            get {
                return ResourceManager.GetString("GmtMinusFourTimeZoneSixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-04:00) Aruba, Barbados, Curaçao, Dominican Rep..
        /// </summary>
        internal static string GmtMinusFourTimeZoneThird {
            get {
                return ResourceManager.GetString("GmtMinusFourTimeZoneThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-09:30) Marquesas Islands (French Polynesia).
        /// </summary>
        internal static string GmtMinusNineThirtyTimeZone {
            get {
                return ResourceManager.GetString("GmtMinusNineThirtyTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-09:00) Alaska.
        /// </summary>
        internal static string GmtMinusNineTimeZone {
            get {
                return ResourceManager.GetString("GmtMinusNineTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-09:00) Gambier Islands (French Polynesia).
        /// </summary>
        internal static string GmtMinusNineTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtMinusNineTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-01:00) Azores.
        /// </summary>
        internal static string GmtMinusOneTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtMinusOneTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-01:00) Cabo Verde Is..
        /// </summary>
        internal static string GmtMinusOneTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtMinusOneTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-07:00) Mountain Time (US &amp; Canada).
        /// </summary>
        internal static string GmtMinusSevenTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtMinusSevenTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-07:00) Chihuahua, La Paz, Mazatlan.
        /// </summary>
        internal static string GmtMinusSevenTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtMinusSevenTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-07:00) Arizona (US).
        /// </summary>
        internal static string GmtMinusSevenTimeZoneThird {
            get {
                return ResourceManager.GetString("GmtMinusSevenTimeZoneThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-06:00) Central Time (US &amp; Canada).
        /// </summary>
        internal static string GmtMinusSixTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtMinusSixTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-06:00) Belize, Costa Rica, Guatemala, Honduras.
        /// </summary>
        internal static string GmtMinusSixTimeZoneFourth {
            get {
                return ResourceManager.GetString("GmtMinusSixTimeZoneFourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-06:00) Guadalajara, Mexico City, Monterrey.
        /// </summary>
        internal static string GmtMinusSixTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtMinusSixTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-06:00) Saskatchewan.
        /// </summary>
        internal static string GmtMinusSixTimeZoneThird {
            get {
                return ResourceManager.GetString("GmtMinusSixTimeZoneThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-10:00) Hawaii, Tahiti (French Polynesia).
        /// </summary>
        internal static string GmtMinusTenTimeZone {
            get {
                return ResourceManager.GetString("GmtMinusTenTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-03:00) Nuuk (Greenland).
        /// </summary>
        internal static string GmtMinusThreeTimeZoneFifth {
            get {
                return ResourceManager.GetString("GmtMinusThreeTimeZoneFifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-03:00) Brasilia.
        /// </summary>
        internal static string GmtMinusThreeTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtMinusThreeTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-03:30) Newfoundland.
        /// </summary>
        internal static string GmtMinusThreeTimeZoneFourth {
            get {
                return ResourceManager.GetString("GmtMinusThreeTimeZoneFourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-03:00) Cayenne, Fortaleza, Paramaribo.
        /// </summary>
        internal static string GmtMinusThreeTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtMinusThreeTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-03:00) Argentina.
        /// </summary>
        internal static string GmtMinusThreeTimeZoneThird {
            get {
                return ResourceManager.GetString("GmtMinusThreeTimeZoneThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-12:00) International Date Line West.
        /// </summary>
        internal static string GmtMinusTwelveTimeZone {
            get {
                return ResourceManager.GetString("GmtMinusTwelveTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT-02:00) South Georgia and the South Sandwich Islands.
        /// </summary>
        internal static string GmtMinusTwoTimeZone {
            get {
                return ResourceManager.GetString("GmtMinusTwoTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+08:00) Singapore.
        /// </summary>
        internal static string GmtPlusEightTimeZoneFifth {
            get {
                return ResourceManager.GetString("GmtPlusEightTimeZoneFifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+08:00) Perth.
        /// </summary>
        internal static string GmtPlusEightTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtPlusEightTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+08:00) Kuala Lumpur.
        /// </summary>
        internal static string GmtPlusEightTimeZoneFourth {
            get {
                return ResourceManager.GetString("GmtPlusEightTimeZoneFourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+08:00) Ulaanbaatar.
        /// </summary>
        internal static string GmtPlusEightTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtPlusEightTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+08:00) Beijing, Chongqing, Hong Kong, Urumqi.
        /// </summary>
        internal static string GmtPlusEightTimeZoneSeventh {
            get {
                return ResourceManager.GetString("GmtPlusEightTimeZoneSeventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+08:00) Taipei.
        /// </summary>
        internal static string GmtPlusEightTimeZoneSixth {
            get {
                return ResourceManager.GetString("GmtPlusEightTimeZoneSixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+08:00) Philippines.
        /// </summary>
        internal static string GmtPlusEightTimeZoneThird {
            get {
                return ResourceManager.GetString("GmtPlusEightTimeZoneThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+11:00) Solomon Is., New Caledonia.
        /// </summary>
        internal static string GmtPlusElevenTimeZone {
            get {
                return ResourceManager.GetString("GmtPlusElevenTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+11:00) Bougainville Island.
        /// </summary>
        internal static string GmtPlusElevenTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtPlusElevenTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+05:00) Ashgabat, Tashkent.
        /// </summary>
        internal static string GmtPlusFiveTimeZoneFifth {
            get {
                return ResourceManager.GetString("GmtPlusFiveTimeZoneFifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+05:45) Kathmandu.
        /// </summary>
        internal static string GmtPlusFiveTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtPlusFiveTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+05:00) Islamabad, Karachi.
        /// </summary>
        internal static string GmtPlusFiveTimeZoneFourth {
            get {
                return ResourceManager.GetString("GmtPlusFiveTimeZoneFourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+05:30) Chennai, Kolkata, Mumbai, New Delhi, Sri Jayawardenepura.
        /// </summary>
        internal static string GmtPlusFiveTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtPlusFiveTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+05:00) Maldives.
        /// </summary>
        internal static string GmtPlusFiveTimeZoneThird {
            get {
                return ResourceManager.GetString("GmtPlusFiveTimeZoneThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+14:00) Kiritimati Island.
        /// </summary>
        internal static string GmtPlusFourteenTimeZone {
            get {
                return ResourceManager.GetString("GmtPlusFourteenTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+04:30) Kabul.
        /// </summary>
        internal static string GmtPlusFourTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtPlusFourTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+04:00) Baku.
        /// </summary>
        internal static string GmtPlusFourTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtPlusFourTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+04:00) Abu Dhabi, Muscat, Port Louis.
        /// </summary>
        internal static string GmtPlusFourTimeZoneThird {
            get {
                return ResourceManager.GetString("GmtPlusFourTimeZoneThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+09:00) Osaka, Sapporo, Tokyo.
        /// </summary>
        internal static string GmtPlusNineTimeThird {
            get {
                return ResourceManager.GetString("GmtPlusNineTimeThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+09:00) Palau, Timor-Leste.
        /// </summary>
        internal static string GmtPlusNineTimeZoneFifth {
            get {
                return ResourceManager.GetString("GmtPlusNineTimeZoneFifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+09:30) Adelaide.
        /// </summary>
        internal static string GmtPlusNineTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtPlusNineTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+09:00) Seoul.
        /// </summary>
        internal static string GmtPlusNineTimeZoneFourth {
            get {
                return ResourceManager.GetString("GmtPlusNineTimeZoneFourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+09:30) Darwin.
        /// </summary>
        internal static string GmtPlusNineTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtPlusNineTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+09:00) Chita, Yakutsk, Blagoveschensk.
        /// </summary>
        internal static string GmtPlusNineTimeZoneSixth {
            get {
                return ResourceManager.GetString("GmtPlusNineTimeZoneSixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+01:00) Copenhagen, Oslo, Stockholm.
        /// </summary>
        internal static string GmtPlusOneTimeZoneFifth {
            get {
                return ResourceManager.GetString("GmtPlusOneTimeZoneFifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+01:00) Sarajevo, Skopje, Warsaw, Zagreb.
        /// </summary>
        internal static string GmtPlusOneTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtPlusOneTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague.
        /// </summary>
        internal static string GmtPlusOneTimeZoneFourth {
            get {
                return ResourceManager.GetString("GmtPlusOneTimeZoneFourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+01:00) Brussels, Copenhagen, Madrid, Paris.
        /// </summary>
        internal static string GmtPlusOneTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtPlusOneTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+01:00) Algeria, Angola, Congo, Nigeria, Tunisia.
        /// </summary>
        internal static string GmtPlusOneTimeZoneSeventh {
            get {
                return ResourceManager.GetString("GmtPlusOneTimeZoneSeventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+01:00) Windhoek.
        /// </summary>
        internal static string GmtPlusOneTimeZoneSixth {
            get {
                return ResourceManager.GetString("GmtPlusOneTimeZoneSixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna.
        /// </summary>
        internal static string GmtPlusOneTimeZoneThird {
            get {
                return ResourceManager.GetString("GmtPlusOneTimeZoneThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+07:00) Novosibirsk.
        /// </summary>
        internal static string GmtPlusSevenTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtPlusSevenTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+07:00) Bangkok, Hanoi, Jakarta.
        /// </summary>
        internal static string GmtPlusSevenTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtPlusSevenTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+06:00) Omsk.
        /// </summary>
        internal static string GmtPlusSixTimeZoneFifth {
            get {
                return ResourceManager.GetString("GmtPlusSixTimeZoneFifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+06:30) Yangon (Rangoon), Cocos (Keeling) Is..
        /// </summary>
        internal static string GmtPlusSixTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtPlusSixTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+06:00) Bishkek.
        /// </summary>
        internal static string GmtPlusSixTimeZoneFourth {
            get {
                return ResourceManager.GetString("GmtPlusSixTimeZoneFourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+06:00) Dhaka.
        /// </summary>
        internal static string GmtPlusSixTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtPlusSixTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+06:00) Astana.
        /// </summary>
        internal static string GmtPlusSixTimeZoneThird {
            get {
                return ResourceManager.GetString("GmtPlusSixTimeZoneThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+10:00) Guam, Port Moresby.
        /// </summary>
        internal static string GmtPlusTenTimeZoneFifth {
            get {
                return ResourceManager.GetString("GmtPlusTenTimeZoneFifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+10:00) Canberra, Melbourne, Sydney.
        /// </summary>
        internal static string GmtPlusTenTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtPlusTenTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+10:00) Brisbane.
        /// </summary>
        internal static string GmtPlusTenTimeZoneSixth {
            get {
                return ResourceManager.GetString("GmtPlusTenTimeZoneSixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+10:00) Hobart.
        /// </summary>
        internal static string GmtPlusTenTimeZoneThird {
            get {
                return ResourceManager.GetString("GmtPlusTenTimeZoneThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+13:00) Samoa.
        /// </summary>
        internal static string GmtPlusThirteenTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtPlusThirteenTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+13:00) Nuku&apos;alofa.
        /// </summary>
        internal static string GmtPlusThirteenTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtPlusThirteenTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+13:00) Tokelau.
        /// </summary>
        internal static string GmtPlusThirteenTimeZoneThird {
            get {
                return ResourceManager.GetString("GmtPlusThirteenTimeZoneThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+03:00) Istanbul.
        /// </summary>
        internal static string GmtPlusThreeTimeZoneEighth {
            get {
                return ResourceManager.GetString("GmtPlusThreeTimeZoneEighth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+03:00) Riyadh, Kuwait City, Doha, Manama.
        /// </summary>
        internal static string GmtPlusThreeTimeZoneFifth {
            get {
                return ResourceManager.GetString("GmtPlusThreeTimeZoneFifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+03:30) Tehran.
        /// </summary>
        internal static string GmtPlusThreeTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtPlusThreeTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+03:00) Nairobi.
        /// </summary>
        internal static string GmtPlusThreeTimeZoneFourth {
            get {
                return ResourceManager.GetString("GmtPlusThreeTimeZoneFourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+03:00) Minsk.
        /// </summary>
        internal static string GmtPlusThreeTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtPlusThreeTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+03:00) Moscow, St. Petersburg, Volgograd.
        /// </summary>
        internal static string GmtPlusThreeTimeZoneSeventh {
            get {
                return ResourceManager.GetString("GmtPlusThreeTimeZoneSeventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+03:00) Baghdad.
        /// </summary>
        internal static string GmtPlusThreeTimeZoneSixth {
            get {
                return ResourceManager.GetString("GmtPlusThreeTimeZoneSixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+03:00) Madagascar.
        /// </summary>
        internal static string GmtPlusThreeTimeZoneThird {
            get {
                return ResourceManager.GetString("GmtPlusThreeTimeZoneThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+12:45) Chatham Islands.
        /// </summary>
        internal static string GmtPlusTwelveFortyFiveTimeZone {
            get {
                return ResourceManager.GetString("GmtPlusTwelveFortyFiveTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+12:00) Fiji.
        /// </summary>
        internal static string GmtPlusTwelveTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtPlusTwelveTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+12:00) Marshall Is., Tuvalu.
        /// </summary>
        internal static string GmtPlusTwelveTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtPlusTwelveTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+12:00) Auckland, Wellington.
        /// </summary>
        internal static string GmtPlusTwelveTimeZoneThird {
            get {
                return ResourceManager.GetString("GmtPlusTwelveTimeZoneThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+02:00) Tripoli.
        /// </summary>
        internal static string GmtPlusTwoTimeZoneEighth {
            get {
                return ResourceManager.GetString("GmtPlusTwoTimeZoneEighth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+02:00) Kiev.
        /// </summary>
        internal static string GmtPlusTwoTimeZoneFifth {
            get {
                return ResourceManager.GetString("GmtPlusTwoTimeZoneFifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+02:00) Chisinau, Athens, Bucharest, Nicosia .
        /// </summary>
        internal static string GmtPlusTwoTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtPlusTwoTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius.
        /// </summary>
        internal static string GmtPlusTwoTimeZoneFourth {
            get {
                return ResourceManager.GetString("GmtPlusTwoTimeZoneFourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+02:00) Jerusalem.
        /// </summary>
        internal static string GmtPlusTwoTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtPlusTwoTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+02:00) Harare, Pretoria.
        /// </summary>
        internal static string GmtPlusTwoTimeZoneSeventh {
            get {
                return ResourceManager.GetString("GmtPlusTwoTimeZoneSeventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+02:00) Cairo.
        /// </summary>
        internal static string GmtPlusTwoTimeZoneSixth {
            get {
                return ResourceManager.GetString("GmtPlusTwoTimeZoneSixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+02:00) Amman, Deirut, Damascus.
        /// </summary>
        internal static string GmtPlusTwoTimeZoneThird {
            get {
                return ResourceManager.GetString("GmtPlusTwoTimeZoneThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+00:00) Dublin, Edinburgh, Lisbon, London.
        /// </summary>
        internal static string GmtTimeZoneFirst {
            get {
                return ResourceManager.GetString("GmtTimeZoneFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+00:00) Casablanca.
        /// </summary>
        internal static string GmtTimeZoneForth {
            get {
                return ResourceManager.GetString("GmtTimeZoneForth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+00:00) Reykjavik.
        /// </summary>
        internal static string GmtTimeZoneSecond {
            get {
                return ResourceManager.GetString("GmtTimeZoneSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (GMT+00:00) Monrovia, Ouagadougou, Dakar, Yamoussoukro.
        /// </summary>
        internal static string GmtTimeZoneThird {
            get {
                return ResourceManager.GetString("GmtTimeZoneThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed when profile is assigned..
        /// </summary>
        internal static string InstallManifestToolTip {
            get {
                return ResourceManager.GetString("InstallManifestToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I Understand.
        /// </summary>
        internal static string IUnderstand {
            get {
                return ResourceManager.GetString("IUnderstand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More &amp; Upgrade.
        /// </summary>
        internal static string LearnAndUpgrade {
            get {
                return ResourceManager.GetString("LearnAndUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More About Cloud Services.
        /// </summary>
        internal static string LearnMoreAboutCloudServices {
            get {
                return ResourceManager.GetString("LearnMoreAboutCloudServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log into customer type Organization Group to continue..
        /// </summary>
        internal static string LoginToCustomerTypeOgForDataIntegration {
            get {
                return ResourceManager.GetString("LoginToCustomerTypeOgForDataIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Services.
        /// </summary>
        internal static string MyServices {
            get {
                return ResourceManager.GetString("MyServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like you don&apos;t have any data.
        /// </summary>
        internal static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: you will need to save the file as a .csv before importing..
        /// </summary>
        internal static string NoteYouWillNeedToSaveTheFileAsA_csvBeforeImporting {
            get {
                return ResourceManager.GetString("NoteYouWillNeedToSaveTheFileAsA_csvBeforeImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation not supported.
        /// </summary>
        internal static string OperationNotSupported {
            get {
                return ResourceManager.GetString("OperationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provisioning Package Notification.
        /// </summary>
        internal static string ProvisioningPackageNotification {
            get {
                return ResourceManager.GetString("ProvisioningPackageNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember.
        /// </summary>
        internal static string Remember {
            get {
                return ResourceManager.GetString("Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removal Manifest.
        /// </summary>
        internal static string RemoveManifest {
            get {
                return ResourceManager.GetString("RemoveManifest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executed when profile is unassigned..
        /// </summary>
        internal static string RemoveManifestToolTip {
            get {
                return ResourceManager.GetString("RemoveManifestToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Bios Password Confirmed.
        /// </summary>
        internal static string ResetBiosPasswordConfirmed {
            get {
                return ResourceManager.GetString("ResetBiosPasswordConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Bios Password Failed.
        /// </summary>
        internal static string ResetBiosPasswordFailed {
            get {
                return ResourceManager.GetString("ResetBiosPasswordFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Bios Password Refused.
        /// </summary>
        internal static string ResetBiosPasswordRefused {
            get {
                return ResourceManager.GetString("ResetBiosPasswordRefused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Bios Password Requested.
        /// </summary>
        internal static string ResetBiosPasswordRequested {
            get {
                return ResourceManager.GetString("ResetBiosPasswordRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in {0} list view.
        /// </summary>
        internal static string SearchInArgListView {
            get {
                return ResourceManager.GetString("SearchInArgListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UEM.
        /// </summary>
        internal static string UEM {
            get {
                return ResourceManager.GetString("UEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this resource. Contact your IT administrator if you believe you received this message in error..
        /// </summary>
        internal static string UnAuthorizedAccessWarningMessage {
            get {
                return ResourceManager.GetString("UnAuthorizedAccessWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something unexpected happened. If the issue persists, please contact your IT administrator..
        /// </summary>
        internal static string UnrecoverableErrorDescription {
            get {
                return ResourceManager.GetString("UnrecoverableErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace ONE UEM Data Integration.
        /// </summary>
        internal static string WorkspaceOneUemDataIntegration {
            get {
                return ResourceManager.GetString("WorkspaceOneUemDataIntegration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration with Workspace ONE Intelligence requires user and event data from Workspace ONE UEM..
        /// </summary>
        internal static string WorkspaceOneUemDataIntegrationDescription1 {
            get {
                return ResourceManager.GetString("WorkspaceOneUemDataIntegrationDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you accept, you authorize sending this data from Workspace ONE UEM to Workspace ONE Intelligence and you will be redirected to Workspace ONE Intelligence..
        /// </summary>
        internal static string WorkspaceOneUemDataIntegrationDescription2 {
            get {
                return ResourceManager.GetString("WorkspaceOneUemDataIntegrationDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you decline, you will be redirected to Workspace ONE Intelligence without Workspace ONE UEM data integration..
        /// </summary>
        internal static string WorkspaceOneUemDataIntegrationDescription3 {
            get {
                return ResourceManager.GetString("WorkspaceOneUemDataIntegrationDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified Workspace ONE UEM tenant has been already bound to an Intelligence Tenant..
        /// </summary>
        internal static string WorkspaceOneUemIsAlreadyBoundToIntelligence {
            get {
                return ResourceManager.GetString("WorkspaceOneUemIsAlreadyBoundToIntelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace ONE.
        /// </summary>
        internal static string WS1CloudPlatform {
            get {
                return ResourceManager.GetString("WS1CloudPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace ONE Hub Services.
        /// </summary>
        internal static string WS1HubServices {
            get {
                return ResourceManager.GetString("WS1HubServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace ONE Access.
        /// </summary>
        internal static string WS1IdentityManager {
            get {
                return ResourceManager.GetString("WS1IdentityManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace ONE Intelligence.
        /// </summary>
        internal static string WS1Intelligence {
            get {
                return ResourceManager.GetString("WS1Intelligence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace ONE UEM.
        /// </summary>
        internal static string WS1OneUEM {
            get {
                return ResourceManager.GetString("WS1OneUEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XLSX.
        /// </summary>
        internal static string XLSX {
            get {
                return ResourceManager.GetString("XLSX", resourceCulture);
            }
        }
    }
}
