name: 'Get commit range'
outputs:
  commit-range:
    description: "Commit range"
    value: ${{ steps.get-commit-range-id.outputs.commit-range }}
runs:
  using: "composite"
  steps:
    - name: Extract commit id range
      id: get-commit-range-id
      shell: bash
      run: |
        echo "event name: ${{ github.event_name }}"
        if [ x${{ github.event_name }} = xpush ]; then
          LAST_COMMIT_ID=$(git log -n 1 --pretty=format:"%H")
          SECOND_LAST_COMMIT_ID=$(git log -n 1 --skip 1 --pretty=format:"%H")
          COMMIT_RANGE="${SECOND_LAST_COMMIT_ID} ${LAST_COMMIT_ID}"
        fi
        if [ x${{ github.event_name }} = xpull_request ]; then
          MERGE_COMMIT_RANGE=$(git log -n 1 | sed -n "/Merge\ .* into .*/p" | sed 's/.*Merge //' | sed 's/into //')
          COMMIT_RANGE="${MERGE_COMMIT_RANGE}"
        fi
        echo "::set-output name=commit-range::$(echo $COMMIT_RANGE)"
        echo 'The commit id range is' ${COMMIT_RANGE}
