//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WanderingWiFi.AirWatch.Globalization.Resources.Freestyle {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LabelValues {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelValues() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WanderingWiFi.AirWatch.Globalization.Resources.Freestyle.LabelValues", typeof(LabelValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About Freestyle Orchestrator.
        /// </summary>
        internal static string AboutFreestyleOrchestrator {
            get {
                return ResourceManager.GetString("AboutFreestyleOrchestrator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add/Edit Freestyle.
        /// </summary>
        internal static string AddEditFreestyle {
            get {
                return ResourceManager.GetString("AddEditFreestyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Control access to create, edit and publish freestyle and resource types like apps, profiles &amp; scripts.
        /// </summary>
        internal static string AddEditFreestyleHelp {
            get {
                return ResourceManager.GetString("AddEditFreestyleHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Address Width.
        /// </summary>
        internal static string AddressWidth {
            get {
                return ResourceManager.GetString("AddressWidth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application does not exist.
        /// </summary>
        internal static string ApplicationDoesNotExist {
            get {
                return ResourceManager.GetString("ApplicationDoesNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Application Exists.
        /// </summary>
        internal static string ApplicationExists {
            get {
                return ResourceManager.GetString("ApplicationExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The actual number of potentially qualified apps might be greater than shown..
        /// </summary>
        internal static string AppResultsDescription {
            get {
                return ResourceManager.GetString("AppResultsDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Apps {0} - {1} of {2}.
        /// </summary>
        internal static string AppsOfArg {
            get {
                return ResourceManager.GetString("AppsOfArg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Archived.
        /// </summary>
        internal static string Archived {
            get {
                return ResourceManager.GetString("Archived", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Assignment does not exist or might have been deleted..
        /// </summary>
        internal static string AssignmentDoesNotExistOrMightBeDeleted {
            get {
                return ResourceManager.GetString("AssignmentDoesNotExistOrMightBeDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve assignments..
        /// </summary>
        internal static string AssignmentsCouldNotBeRetrieved {
            get {
                return ResourceManager.GetString("AssignmentsCouldNotBeRetrieved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        internal static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto Deploy.
        /// </summary>
        internal static string AutoDeploy
        {
            get
            {
                return ResourceManager.GetString("AutoDeploy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Auto Deploy and Show in App Catalog.
        /// </summary>
        internal static string AutoDeployAndShowInAppCatalog {
            get {
                return ResourceManager.GetString("AutoDeployAndShowInAppCatalog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Backoff Rate.
        /// </summary>
        internal static string BackoffRate {
            get {
                return ResourceManager.GetString("BackoffRate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiplier that determines the interval between subsequent retries..
        /// </summary>
        internal static string BackoffRateDesc {
            get {
                return ResourceManager.GetString("BackoffRateDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bank Locator.
        /// </summary>
        internal static string BankLocator {
            get {
                return ResourceManager.GetString("BankLocator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Make sure Dell Command Monitor app is added to the workflow before publishing..
        /// </summary>
        internal static string BiosPayloadWarning {
            get {
                return ResourceManager.GetString("BiosPayloadWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bitlocker.
        /// </summary>
        internal static string Bitlocker {
            get {
                return ResourceManager.GetString("Bitlocker", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browser Extension.
        /// </summary>
        internal static string BrowserExtension {
            get {
                return ResourceManager.GetString("BrowserExtension", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Browser Name.
        /// </summary>
        internal static string BrowserName {
            get {
                return ResourceManager.GetString("BrowserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        internal static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GIF or PNG...
        /// </summary>
        internal static string CatalogIconRecommendationAndLimit
        {
            get
            {
                return ResourceManager.GetString("CatalogIconRecommendationAndLimit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string ChangeAttribute {
            get {
                return ResourceManager.GetString("ChangeAttribute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Changing this selection erases all of the attributes associated with the current selection..
        /// </summary>
        internal static string ChangeAttributeConfirmationDescription {
            get {
                return ResourceManager.GetString("ChangeAttributeConfirmationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change Selection.
        /// </summary>
        internal static string ChangeAttributeConfirmationTitle {
            get {
                return ResourceManager.GetString("ChangeAttributeConfirmationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change Platform.
        /// </summary>
        internal static string ChangePlatform {
            get {
                return ResourceManager.GetString("ChangePlatform", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Chasis Type.
        /// </summary>
        internal static string ChasisType {
            get {
                return ResourceManager.GetString("ChasisType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clock Speed.
        /// </summary>
        internal static string ClockSpeed {
            get {
                return ResourceManager.GetString("ClockSpeed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code Name.
        /// </summary>
        internal static string CodeName {
            get {
                return ResourceManager.GetString("CodeName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Completed with exception.
        /// </summary>
        internal static string CompletedWithException {
            get {
                return ResourceManager.GetString("CompletedWithException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Compute.
        /// </summary>
        internal static string Compute {
            get {
                return ResourceManager.GetString("Compute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select platform to add more steps to the workflow..
        /// </summary>
        internal static string ConfigurationOptionTooltipMsg {
            get {
                return ResourceManager.GetString("ConfigurationOptionTooltipMsg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        internal static string ConfirmDeleteArg {
            get {
                return ResourceManager.GetString("ConfirmDeleteArg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deleting this workflow will remove the resource assignment from the devices in this workflow. This action cannot be undone. Resources currently installed on the devices will remain unless manually removed..
        /// </summary>
        internal static string ConfirmDeleteWorkflowContent {
            get {
                return ResourceManager.GetString("ConfirmDeleteWorkflowContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pause {0}.
        /// </summary>
        internal static string ConfirmPauseArg {
            get {
                return ResourceManager.GetString("ConfirmPauseArg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This action stops the workflow from running on new devices until you resume it. Devices that have run or are currently running the workflow are not affected..
        /// </summary>
        internal static string ConfirmPauseWorkflowContent {
            get {
                return ResourceManager.GetString("ConfirmPauseWorkflowContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connection Id.
        /// </summary>
        internal static string ConnectionId {
            get {
                return ResourceManager.GetString("ConnectionId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cores.
        /// </summary>
        internal static string Cores {
            get {
                return ResourceManager.GetString("Cores", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        internal static string CPU {
            get {
                return ResourceManager.GetString("CPU", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU Brand.
        /// </summary>
        internal static string CPUBrand {
            get {
                return ResourceManager.GetString("CPUBrand", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU ID.
        /// </summary>
        internal static string CPUID {
            get {
                return ResourceManager.GetString("CPUID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU Model.
        /// </summary>
        internal static string CPUModel {
            get {
                return ResourceManager.GetString("CPUModel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU SubType.
        /// </summary>
        internal static string CPUSubType {
            get {
                return ResourceManager.GetString("CPUSubType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPU Type.
        /// </summary>
        internal static string CPUType {
            get {
                return ResourceManager.GetString("CPUType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Created on {0} by {1}.
        /// </summary>
        internal static string CreatedOnByArg {
            get {
                return ResourceManager.GetString("CreatedOnByArg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When you&apos;re ready, click Get Started to create and publish workflows using the resources you’ve configured..
        /// </summary>
        internal static string CreateWorkflowsInfo {
            get {
                return ResourceManager.GetString("CreateWorkflowsInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create your workflows.
        /// </summary>
        internal static string CreateYourWorkflows {
            get {
                return ResourceManager.GetString("CreateYourWorkflows", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data Width.
        /// </summary>
        internal static string DataWidth {
            get {
                return ResourceManager.GetString("DataWidth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete Freestyle.
        /// </summary>
        internal static string DeleteFreestyle {
            get {
                return ResourceManager.GetString("DeleteFreestyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Control access to delete freestyle and resource types like apps, profiles &amp; scripts.
        /// </summary>
        internal static string DeleteFreestyleHelp {
            get {
                return ResourceManager.GetString("DeleteFreestyleHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete workflow.
        /// </summary>
        internal static string DeleteWorkflow {
            get {
                return ResourceManager.GetString("DeleteWorkflow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To remove the installed resources, navigate to the Device Details view for each device, or the Assigned Devices view for each resource..
        /// </summary>
        internal static string DeleteWorkflowAdditionalContent {
            get {
                return ResourceManager.GetString("DeleteWorkflowAdditionalContent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Device Breakdown.
        /// </summary>
        internal static string DeviceBreakdown {
            get {
                return ResourceManager.GetString("DeviceBreakdown", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deployment Settings.
        /// </summary>
        internal static string DeploymentSettings
        {
            get
            {
                return ResourceManager.GetString("DeploymentSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Based on platform and Smart Group selections.
        /// </summary>
        internal static string DeviceExecutionStatusInfo {
            get {
                return ResourceManager.GetString("DeviceExecutionStatusInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Device Locator.
        /// </summary>
        internal static string DeviceLocator {
            get {
                return ResourceManager.GetString("DeviceLocator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Device is not assigned to this workflow..
        /// </summary>
        internal static string DeviceNotAssignedToWorkflow {
            get {
                return ResourceManager.GetString("DeviceNotAssignedToWorkflow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Device with status {0}.
        /// </summary>
        internal static string DeviceWithStatusArg {
            get {
                return ResourceManager.GetString("DeviceWithStatusArg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The status of each step in this Workflow for this device is listed below..
        /// </summary>
        internal static string DeviceWorkflowStatusInfo {
            get {
                return ResourceManager.GetString("DeviceWorkflowStatusInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Disk Index.
        /// </summary>
        internal static string DiskIndex {
            get {
                return ResourceManager.GetString("DiskIndex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DNS Domain.
        /// </summary>
        internal static string DNSDomain {
            get {
                return ResourceManager.GetString("DNSDomain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DNS Server Search Order.
        /// </summary>
        internal static string DNSServerSearchOrder {
            get {
                return ResourceManager.GetString("DNSServerSearchOrder", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        internal static string DoYouWantToContinue {
            get {
                return ResourceManager.GetString("DoYouWantToContinue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Driver Date.
        /// </summary>
        internal static string DriverDate {
            get {
                return ResourceManager.GetString("DriverDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Driver Key.
        /// </summary>
        internal static string DriverKey {
            get {
                return ResourceManager.GetString("DriverKey", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Driver Signed.
        /// </summary>
        internal static string DriverSigned {
            get {
                return ResourceManager.GetString("DriverSigned", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DWORD.
        /// </summary>
        internal static string DWord32Bit {
            get {
                return ResourceManager.GetString("DWord32Bit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Attribute.
        /// </summary>
        internal static string EdiSelectFurther {
            get {
                return ResourceManager.GetString("EdiSelectFurther", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Device counts for the selected step will be available as devices start reporting..
        /// </summary>
        internal static string EmptyStepStatus {
            get {
                return ResourceManager.GetString("EmptyStepStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter a number.
        /// </summary>
        internal static string EnterNumber {
            get {
                return ResourceManager.GetString("EnterNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entry Point.
        /// </summary>
        internal static string EntryBlock {
            get {
                return ResourceManager.GetString("EntryBlock", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Error Handling.
        /// </summary>
        internal static string ErrorHandling {
            get {
                return ResourceManager.GetString("ErrorHandling", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve app categories. If this issue persists, contact your system administrator..
        /// </summary>
        internal static string ErrorLoadingCategories {
            get {
                return ResourceManager.GetString("ErrorLoadingCategories", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to EULA Settings.
        /// </summary>
        internal static string EulaSettings {
            get {
                return ResourceManager.GetString("EulaSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Excluded smartgroup(s) should not be part of smart group assignments of any workflow which contains this application..
        /// </summary>
        internal static string ExcludedSmartGroupAssignmentError {
            get {
                return ResourceManager.GetString("ExcludedSmartGroupAssignmentError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Execution Rate.
        /// </summary>
        internal static string ExecutionRate {
            get {
                return ResourceManager.GetString("ExecutionRate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exists.
        /// </summary>
        internal static string Exists {
            get {
                return ResourceManager.GetString("Exists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Expandable-String.
        /// </summary>
        internal static string ExpandableString {
            get {
                return ResourceManager.GetString("ExpandableString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Extension Name.
        /// </summary>
        internal static string ExtensionName {
            get {
                return ResourceManager.GetString("ExtensionName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File System.
        /// </summary>
        internal static string FileSystem {
            get {
                return ResourceManager.GetString("FileSystem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To find out more visit.
        /// </summary>
        internal static string FindOutMore {
            get {
                return ResourceManager.GetString("FindOutMore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First retry after.
        /// </summary>
        internal static string FirstRetryAfter {
            get {
                return ResourceManager.GetString("FirstRetryAfter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fourth retry after.
        /// </summary>
        internal static string FourthRetryAfter {
            get {
                return ResourceManager.GetString("FourthRetryAfter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Free Space.
        /// </summary>
        internal static string FreeSpace {
            get {
                return ResourceManager.GetString("FreeSpace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Freestyle.
        /// </summary>
        internal static string Freestyle {
            get {
                return ResourceManager.GetString("Freestyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        internal static string FreestyleContext {
            get {
                return ResourceManager.GetString("FreestyleContext", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create workflows that meet your needs.
        /// </summary>
        internal static string FreestyleHeader {
            get {
                return ResourceManager.GetString("FreestyleHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Workspace ONE Freestyle Orchestrator is a no-code IT orchestration platform that gives you the flexibility to create workflows for resources such as apps, profiles, and scripts and apply them to devices based on granular criteria..
        /// </summary>
        internal static string FreestyleInfo {
            get {
                return ResourceManager.GetString("FreestyleInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Currently available for Windows 10 and macOS platforms only..
        /// </summary>
        internal static string FreestyleNote {
            get {
                return ResourceManager.GetString("FreestyleNote", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Freestyle Orchestrator.
        /// </summary>
        internal static string FreestyleOrchestrator {
            get {
                return ResourceManager.GetString("FreestyleOrchestrator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Create workflows for resources such as apps, profiles, and scripts, and apply them to devices based on granular criteria..
        /// </summary>
        internal static string FreestyleOrchestratorInfo {
            get {
                return ResourceManager.GetString("FreestyleOrchestratorInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Freestyle Orchestrator (Preview).
        /// </summary>
        internal static string FreestyleOrchestratorPreview {
            get {
                return ResourceManager.GetString("FreestyleOrchestratorPreview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Freestyle Orchestrator is a low-code IT orchestration platform that gives you the flexibility to create workflows for resources such as apps, profiles, and scripts and apply them to devices based on granular criteria..
        /// </summary>
        internal static string FreestyleWelcomeWindowDescription {
            get {
                return ResourceManager.GetString("FreestyleWelcomeWindowDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Freestyle Orchestrator is currently available for Windows 10 and macOS platforms..
        /// </summary>
        internal static string FreestyleWelcomeWindowDescriptionInfo {
            get {
                return ResourceManager.GetString("FreestyleWelcomeWindowDescriptionInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Freesyle Workflow.
        /// </summary>
        internal static string FreestyleWorkflow {
            get {
                return ResourceManager.GetString("FreestyleWorkflow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deliver objects or take specific action on devices based on criteria..
        /// </summary>
        internal static string FreestyleWorkflowDescription {
            get {
                return ResourceManager.GetString("FreestyleWorkflowDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Getting started with workflows.
        /// </summary>
        internal static string GettingStartedWithWorkflows {
            get {
                return ResourceManager.GetString("GettingStartedWithWorkflows", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hardware Serial.
        /// </summary>
        internal static string HardwareSerial {
            get {
                return ResourceManager.GetString("HardwareSerial", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hardware Vendor.
        /// </summary>
        internal static string HardwareVendor {
            get {
                return ResourceManager.GetString("HardwareVendor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hardware Version.
        /// </summary>
        internal static string HardwareVersion {
            get {
                return ResourceManager.GetString("HardwareVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hotfix.
        /// </summary>
        internal static string Hotfix {
            get {
                return ResourceManager.GetString("Hotfix", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hotfix KB Id.
        /// </summary>
        internal static string HotfixKBId {
            get {
                return ResourceManager.GetString("HotfixKBId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Includes.
        /// </summary>
        internal static string Includes {
            get {
                return ResourceManager.GetString("Includes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Initial Value Is Activated.
        /// </summary>
        internal static string InitialValueIsActivated {
            get {
                return ResourceManager.GetString("InitialValueIsActivated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Initial Value Is Enabled.
        /// </summary>
        internal static string InitialValueIsEnabled {
            get {
                return ResourceManager.GetString("InitialValueIsEnabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Initial Value Is Owned.
        /// </summary>
        internal static string InitialValueIsOwned {
            get {
                return ResourceManager.GetString("InitialValueIsOwned", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installation State.
        /// </summary>
        internal static string InstallationState {
            get {
                return ResourceManager.GetString("InstallationState", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed By.
        /// </summary>
        internal static string InstalledBy {
            get {
                return ResourceManager.GetString("InstalledBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Installed On.
        /// </summary>
        internal static string InstalledOn {
            get {
                return ResourceManager.GetString("InstalledOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Install Location.
        /// </summary>
        internal static string InstallLocation {
            get {
                return ResourceManager.GetString("InstallLocation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Install Source.
        /// </summary>
        internal static string InstallSource {
            get {
                return ResourceManager.GetString("InstallSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Introducing Freestyle Orchestrator.
        /// </summary>
        internal static string IntroducingFreestyleOrchestrator {
            get {
                return ResourceManager.GetString("IntroducingFreestyleOrchestrator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Is Bootable.
        /// </summary>
        internal static string IsBootable {
            get {
                return ResourceManager.GetString("IsBootable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Is Framework.
        /// </summary>
        internal static string IsFramework {
            get {
                return ResourceManager.GetString("IsFramework", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Make sure apps from kiosk payload are added to the workflow before publishing..
        /// </summary>
        internal static string KioskPayloadWarning {
            get {
                return ResourceManager.GetString("KioskPayloadWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last Forty Five Days.
        /// </summary>
        internal static string LastFortyFiveDays {
            get {
                return ResourceManager.GetString("LastFortyFiveDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last Fourteen Days.
        /// </summary>
        internal static string LastFourteenDays {
            get {
                return ResourceManager.GetString("LastFourteenDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last Sixty Days.
        /// </summary>
        internal static string LastSixtyDays {
            get {
                return ResourceManager.GetString("LastSixtyDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        internal static string Latest {
            get {
                return ResourceManager.GetString("Latest", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Latest available.
        /// </summary>
        internal static string LatestAvailable {
            get {
                return ResourceManager.GetString("LatestAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Local Time Zone.
        /// </summary>
        internal static string LocalTimeZone {
            get {
                return ResourceManager.GetString("LocalTimeZone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Logical Drives.
        /// </summary>
        internal static string LogicalDrives {
            get {
                return ResourceManager.GetString("LogicalDrives", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Id.
        /// </summary>
        internal static string ManufacturerId {
            get {
                return ResourceManager.GetString("ManufacturerId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Version.
        /// </summary>
        internal static string ManufacturerVersion {
            get {
                return ResourceManager.GetString("ManufacturerVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Version Info.
        /// </summary>
        internal static string ManufacturerVersionInfo {
            get {
                return ResourceManager.GetString("ManufacturerVersionInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} Match(es) Found.
        /// </summary>
        internal static string MatchesFound {
            get {
                return ResourceManager.GetString("MatchesFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max Clock Speed.
        /// </summary>
        internal static string MaxClockSpeed {
            get {
                return ResourceManager.GetString("MaxClockSpeed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum Retries.
        /// </summary>
        internal static string MaximumRetries {
            get {
                return ResourceManager.GetString("MaximumRetries", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Results might not include.
        /// </summary>
        internal static string MayNotBeFiltered {
            get {
                return ResourceManager.GetString("MayNotBeFiltered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Alphanumeric app versions filtered using &quot;Greater than&quot; or &quot;Less than&quot; operators..
        /// </summary>
        internal static string MayNotBeFilteredDesc {
            get {
                return ResourceManager.GetString("MayNotBeFilteredDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Memory Type.
        /// </summary>
        internal static string MemoryType {
            get {
                return ResourceManager.GetString("MemoryType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Modified on {0} by {1}.
        /// </summary>
        internal static string ModifiedOnByArg {
            get {
                return ResourceManager.GetString("ModifiedOnByArg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monitor performance.
        /// </summary>
        internal static string MonitorPerformance {
            get {
                return ResourceManager.GetString("MonitorPerformance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Monitor and gain insight into published workflows, view performance metrics, and manage saved and archived workflows..
        /// </summary>
        internal static string MonitorWorkflowPerformanceInfo {
            get {
                return ResourceManager.GetString("MonitorWorkflowPerformanceInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Separate multiple values with commas..
        /// </summary>
        internal static string MultipleValueHelpText {
            get {
                return ResourceManager.GetString("MultipleValueHelpText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Must be between {0} and {1}.
        /// </summary>
        internal static string MustBeBetweenArgs {
            get {
                return ResourceManager.GetString("MustBeBetweenArgs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Navigation Freestyle.
        /// </summary>
        internal static string NavigationFreestyle {
            get {
                return ResourceManager.GetString("NavigationFreestyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Control access to freestyle side menu.
        /// </summary>
        internal static string NavigationFreestyleHelp {
            get {
                return ResourceManager.GetString("NavigationFreestyleHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Navigation Resources.
        /// </summary>
        internal static string NavigationResources {
            get {
                return ResourceManager.GetString("NavigationResources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Control access to resources side menu.
        /// </summary>
        internal static string NavigationResourcesHelp {
            get {
                return ResourceManager.GetString("NavigationResourcesHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Network Adapter.
        /// </summary>
        internal static string NetworkAdapter {
            get {
                return ResourceManager.GetString("NetworkAdapter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The version of the app does not have any default policies. Set one before publishing..
        /// </summary>
        internal static string NoDefaultPolicyForVersion {
            get {
                return ResourceManager.GetString("NoDefaultPolicyForVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected step does not have a status associated..
        /// </summary>
        internal static string NoStepStatus {
            get {
                return ResourceManager.GetString("NoStepStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not Between.
        /// </summary>
        internal static string NotBetween {
            get {
                return ResourceManager.GetString("NotBetween", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not Equals.
        /// </summary>
        internal static string NotEquals {
            get {
                return ResourceManager.GetString("NotEquals", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not In.
        /// </summary>
        internal static string NotIn {
            get {
                return ResourceManager.GetString("NotIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Make sure Dell Command Update app is added to the workflow before publishing..
        /// </summary>
        internal static string OemUpdatesPayloadWarning {
            get {
                return ResourceManager.GetString("OemUpdatesPayloadWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Overall Device Execution Status.
        /// </summary>
        internal static string OverallDeviceExecutionStatus {
            get {
                return ResourceManager.GetString("OverallDeviceExecutionStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Overwritten.
        /// </summary>
        internal static string Overwritten {
            get {
                return ResourceManager.GetString("Overwritten", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Partitions.
        /// </summary>
        internal static string Partitions {
            get {
                return ResourceManager.GetString("Partitions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Physical Presence Version.
        /// </summary>
        internal static string PhysicalPresenceVersion {
            get {
                return ResourceManager.GetString("PhysicalPresenceVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Changing the platform will erase all the other resources, steps, actions you have entered into the workflow. Are you sure you want to continue?.
        /// </summary>
        internal static string PlatformChangeConfirmationDescription {
            get {
                return ResourceManager.GetString("PlatformChangeConfirmationDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warning - Platform Change.
        /// </summary>
        internal static string PlatformChangeConfirmationTitle {
            get {
                return ResourceManager.GetString("PlatformChangeConfirmationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resources are filtered based on platform type..
        /// </summary>
        internal static string PlatformDescription {
            get {
                return ResourceManager.GetString("PlatformDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Platform Role.
        /// </summary>
        internal static string PlatformRole {
            get {
                return ResourceManager.GetString("PlatformRole", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Play Demo.
        /// </summary>
        internal static string PlayDemo {
            get {
                return ResourceManager.GetString("PlayDemo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Potentially Qualified Apps.
        /// </summary>
        internal static string PotentiallyImpactedApplications {
            get {
                return ResourceManager.GetString("PotentiallyImpactedApplications", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Else step is not set correctly or missing when using proceed to next step..
        /// </summary>
        internal static string ProceedToNextStepConditionFailedError {
            get {
                return ResourceManager.GetString("ProceedToNextStepConditionFailedError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Product Identification Number.
        /// </summary>
        internal static string ProductIdentificationNumber {
            get {
                return ResourceManager.GetString("ProductIdentificationNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Profiles &amp; Baselines.
        /// </summary>
        internal static string ProfilesAndBaselines {
            get {
                return ResourceManager.GetString("ProfilesAndBaselines", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        internal static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Property File.
        /// </summary>
        internal static string PropertyFile {
            get {
                return ResourceManager.GetString("PropertyFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Protection Status.
        /// </summary>
        internal static string ProtectionStatus {
            get {
                return ResourceManager.GetString("ProtectionStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Published on {0} by {1}.
        /// </summary>
        internal static string PublishedOnByArg {
            get {
                return ResourceManager.GetString("PublishedOnByArg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Publisher Id.
        /// </summary>
        internal static string PublisherId {
            get {
                return ResourceManager.GetString("PublisherId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to QWORD.
        /// </summary>
        internal static string QWord64Bit {
            get {
                return ResourceManager.GetString("QWord64Bit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Re-evaluate Condition.
        /// </summary>
        internal static string ReevaluateCondition {
            get {
                return ResourceManager.GetString("ReevaluateCondition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Executes the entire workflow every 15 minutes to ensure device retains desired state..
        /// </summary>
        internal static string ReevaluateConditionDesc {
            get {
                return ResourceManager.GetString("ReevaluateConditionDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registry.
        /// </summary>
        internal static string Registry {
            get {
                return ResourceManager.GetString("Registry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registry does not exist at.
        /// </summary>
        internal static string RegistryDoesNotExistAt {
            get {
                return ResourceManager.GetString("RegistryDoesNotExistAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registry exists at.
        /// </summary>
        internal static string RegistryExistsAt {
            get {
                return ResourceManager.GetString("RegistryExistsAt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registry Path.
        /// </summary>
        internal static string RegistryPath {
            get {
                return ResourceManager.GetString("RegistryPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Re-install if removed.
        /// </summary>
        internal static string ReinstallIfRemoved {
            get {
                return ResourceManager.GetString("ReinstallIfRemoved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Re-install this resource if it is removed from a device..
        /// </summary>
        internal static string ReinstallIfRemovedDesc {
            get {
                return ResourceManager.GetString("ReinstallIfRemovedDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource Count.
        /// </summary>
        internal static string ResourceCount {
            get {
                return ResourceManager.GetString("ResourceCount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve re-organized the left navigation pane (main menu) to include a new Resources tab so you can more easily access and manage commonly used features. In Resources, you’ll find apps, profiles, conditions, and more..
        /// </summary>
        internal static string ResourcesWelcomeWindowDescription {
            get {
                return ResourceManager.GetString("ResourcesWelcomeWindowDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this resource. For assistance, contact your system administrator..
        /// </summary>
        internal static string ResourceUnauthorizedAccessContactSystemAdmin {
            get {
                return ResourceManager.GetString("ResourceUnauthorizedAccessContactSystemAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restore To Default.
        /// </summary>
        internal static string RestoreToDefault {
            get {
                return ResourceManager.GetString("RestoreToDefault", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retry After.
        /// </summary>
        internal static string RetryAfter {
            get {
                return ResourceManager.GetString("RetryAfter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Time interval after which workflow steps with errors are retried..
        /// </summary>
        internal static string RetryAfterDesc {
            get {
                return ResourceManager.GetString("RetryAfterDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Product of Retry After, Retry Number and Backoff Rate..
        /// </summary>
        internal static string RetryIntervalDesc {
            get {
                return ResourceManager.GetString("RetryIntervalDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Run Script.
        /// </summary>
        internal static string RunScript {
            get {
                return ResourceManager.GetString("RunScript", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to save. Try again. If the issue persists, contact your system administrator..
        /// </summary>
        internal static string SavedFailedContactAdmin {
            get {
                return ResourceManager.GetString("SavedFailedContactAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workflow failed to publish. Workflow was saved, try publish again..
        /// </summary>
        internal static string SaveSuccessPublishFailedTryAgain {
            get {
                return ResourceManager.GetString("SaveSuccessPublishFailedTryAgain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search and Select.
        /// </summary>
        internal static string SearchAndSelect {
            get {
                return ResourceManager.GetString("SearchAndSelect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search for an existing application.
        /// </summary>
        internal static string SearchExistingApp {
            get {
                return ResourceManager.GetString("SearchExistingApp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search for an existing profile.
        /// </summary>
        internal static string SearchExistingProfile {
            get {
                return ResourceManager.GetString("SearchExistingProfile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search Script.
        /// </summary>
        internal static string SearchScript {
            get {
                return ResourceManager.GetString("SearchScript", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Second retry after.
        /// </summary>
        internal static string SecondRetryAfter {
            get {
                return ResourceManager.GetString("SecondRetryAfter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select the Smart Groups...
        /// </summary>
        internal static string SelectSmartGroupMessage
        {
            get
            {
                return ResourceManager.GetString("SelectSmartGroupMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Version.
        /// </summary>
        internal static string SelectVersion {
            get {
                return ResourceManager.GetString("SelectVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set Default Policy.
        /// </summary>
        internal static string SetDefaultPolicy {
            get {
                return ResourceManager.GetString("SetDefaultPolicy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set Registry Data.
        /// </summary>
        internal static string SetRegistryData {
            get {
                return ResourceManager.GetString("SetRegistryData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Set Registry Value.
        /// </summary>
        internal static string SetRegistryValue {
            get {
                return ResourceManager.GetString("SetRegistryValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving workflow settings.
        /// </summary>
        internal static string SettingsRetrievalError {
            get {
                return ResourceManager.GetString("SettingsRetrievalError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workflow settings saved successfully.
        /// </summary>
        internal static string SettingsSavedSuccessfully {
            get {
                return ResourceManager.GetString("SettingsSavedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving workflow settings. Please try again.
        /// </summary>
        internal static string SettingsSaveFailedTryAgain {
            get {
                return ResourceManager.GetString("SettingsSaveFailedTryAgain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Shares.
        /// </summary>
        internal static string Shares {
            get {
                return ResourceManager.GetString("Shares", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        internal static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Showing {0} results.
        /// </summary>
        internal static string ShowingResultsArg {
            get {
                return ResourceManager.GetString("ShowingResultsArg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skip Workflow Step.
        /// </summary>
        internal static string SkipWorkflow {
            get {
                return ResourceManager.GetString("SkipWorkflow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Skip the failed workflow step and report an error, but continue the workflow..
        /// </summary>
        internal static string SkipWorkflowDesc {
            get {
                return ResourceManager.GetString("SkipWorkflowDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Socket Designation.
        /// </summary>
        internal static string SocketDesignation {
            get {
                return ResourceManager.GetString("SocketDesignation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spec Version.
        /// </summary>
        internal static string SpecVersion {
            get {
                return ResourceManager.GetString("SpecVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Navigate to Resources and configure apps, profiles, scripts, and sensors to reference within a workflow..
        /// </summary>
        internal static string StageWorkflowInfo {
            get {
                return ResourceManager.GetString("StageWorkflowInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stage workflow resources.
        /// </summary>
        internal static string StageWorkflowResources {
            get {
                return ResourceManager.GetString("StageWorkflowResources", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start exploring Freestyle Orchestrator.
        /// </summary>
        internal static string StartExploringFreestyleOrchestrator {
            get {
                return ResourceManager.GetString("StartExploringFreestyleOrchestrator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start Type.
        /// </summary>
        internal static string StartType {
            get {
                return ResourceManager.GetString("StartType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to State Name.
        /// </summary>
        internal static string StateName {
            get {
                return ResourceManager.GetString("StateName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Step Status.
        /// </summary>
        internal static string StepStatus {
            get {
                return ResourceManager.GetString("StepStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop Workflow.
        /// </summary>
        internal static string StopWorkflow {
            get {
                return ResourceManager.GetString("StopWorkflow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Stop the workflow at the failed step and report a failed status..
        /// </summary>
        internal static string StopWorkflowDesc {
            get {
                return ResourceManager.GetString("StopWorkflowDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace with Time Window.
        /// </summary>
        internal static string SwitchToTimeWindow {
            get {
                return ResourceManager.GetString("SwitchToTimeWindow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Would you like to replace this condition with a time window?.
        /// </summary>
        internal static string SwitchToTimeWindowConfirmation {
            get {
                return ResourceManager.GetString("SwitchToTimeWindowConfirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A time window condition cannot be combined with other conditions. Adding a time window will replace existing criteria..
        /// </summary>
        internal static string SwitchToTimeWindowWarning {
            get {
                return ResourceManager.GetString("SwitchToTimeWindowWarning", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to System Enclosure.
        /// </summary>
        internal static string SystemEnclosure {
            get {
                return ResourceManager.GetString("SystemEnclosure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to What would you like to create a workflow for?.
        /// </summary>
        internal static string TemplateSelectionQuestion {
            get {
                return ResourceManager.GetString("TemplateSelectionQuestion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Third retry after.
        /// </summary>
        internal static string ThirdRetryAfter {
            get {
                return ResourceManager.GetString("ThirdRetryAfter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string TimeDurationDay {
            get {
                return ResourceManager.GetString("TimeDurationDay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Day(s).
        /// </summary>
        internal static string TimeDurationDays {
            get {
                return ResourceManager.GetString("TimeDurationDays", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        internal static string TimeDurationHour {
            get {
                return ResourceManager.GetString("TimeDurationHour", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hour(s).
        /// </summary>
        internal static string TimeDurationHours {
            get {
                return ResourceManager.GetString("TimeDurationHours", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        internal static string TimeDurationMinute {
            get {
                return ResourceManager.GetString("TimeDurationMinute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Minute(s).
        /// </summary>
        internal static string TimeDurationMinutes {
            get {
                return ResourceManager.GetString("TimeDurationMinutes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maximum time to wait for a workflow step to complete..
        /// </summary>
        internal static string TimeoutDesc {
            get {
                return ResourceManager.GetString("TimeoutDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Time Reported.
        /// </summary>
        internal static string TimeReported {
            get {
                return ResourceManager.GetString("TimeReported", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The condition re-evaluates at a configured interval until the device meets it. ELSE branches are not allowed..
        /// </summary>
        internal static string TimeWindowRuleDescription {
            get {
                return ResourceManager.GetString("TimeWindowRuleDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The condition re-evaluates at a configured interval ({0}) until the device meets it. ELSE branches are not allowed..
        /// </summary>
        internal static string TimeWindowRuleDescriptionArg {
            get {
                return ResourceManager.GetString("TimeWindowRuleDescriptionArg", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to State management cannot be applied to a time window condition..
        /// </summary>
        internal static string TimeWindowStateSupport {
            get {
                return ResourceManager.GetString("TimeWindowStateSupport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To learn more.
        /// </summary>
        internal static string ToLearnMore {
            get {
                return ResourceManager.GetString("ToLearnMore", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total Eligible Devices.
        /// </summary>
        internal static string TotalEligibleDevices {
            get {
                return ResourceManager.GetString("TotalEligibleDevices", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Troubleshoot.
        /// </summary>
        internal static string Troubleshoot {
            get {
                return ResourceManager.GetString("Troubleshoot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Trusted Platform Module.
        /// </summary>
        internal static string TrustedPlatformModule {
            get {
                return ResourceManager.GetString("TrustedPlatformModule", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this resource. For assistance, contact your IT administrator..
        /// </summary>
        internal static string UnauthorizedAccessResource {
            get {
                return ResourceManager.GetString("UnauthorizedAccessResource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Uninstaller File Path.
        /// </summary>
        internal static string UninstallerFilePath {
            get {
                return ResourceManager.GetString("UninstallerFilePath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Universally unique identifier.
        /// </summary>
        internal static string Universallyuniqueidentifier {
            get {
                return ResourceManager.GetString("Universallyuniqueidentifier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workflow cannot contain a profile with an escrow payload. Select a different profile..
        /// </summary>
        internal static string UnsupportedProfilePayloadEcrow {
            get {
                return ResourceManager.GetString("UnsupportedProfilePayloadEcrow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update Agent.
        /// </summary>
        internal static string UpdateAgent {
            get {
                return ResourceManager.GetString("UpdateAgent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UUID.
        /// </summary>
        internal static string Uuid {
            get {
                return ResourceManager.GetString("Uuid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version UUID.
        /// </summary>
        internal static string VersionUUID {
            get {
                return ResourceManager.GetString("VersionUUID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter version as numbers separated by periods (1.0, 1.0.1, 1.0.1.1)..
        /// </summary>
        internal static string VersionValidationMessage {
            get {
                return ResourceManager.GetString("VersionValidationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View Docs.
        /// </summary>
        internal static string ViewDocs {
            get {
                return ResourceManager.GetString("ViewDocs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View Freestyle.
        /// </summary>
        internal static string ViewFreestyle {
            get {
                return ResourceManager.GetString("ViewFreestyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Control access to view freestyle details and resource types like apps, profiles &amp; scripts.
        /// </summary>
        internal static string ViewFreestyleHelp {
            get {
                return ResourceManager.GetString("ViewFreestyleHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View In Modal.
        /// </summary>
        internal static string ViewInModal {
            get {
                return ResourceManager.GetString("ViewInModal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View Details.
        /// </summary>
        internal static string ViewItemDetails {
            get {
                return ResourceManager.GetString("ViewItemDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View Results.
        /// </summary>
        internal static string ViewResults {
            get {
                return ResourceManager.GetString("ViewResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Virtual Apps Collections.
        /// </summary>
        internal static string VirtualAppsCollections {
            get {
                return ResourceManager.GetString("VirtualAppsCollections", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Virtual CPU.
        /// </summary>
        internal static string VirtualCPU {
            get {
                return ResourceManager.GetString("VirtualCPU", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Virtual CPUs.
        /// </summary>
        internal static string VirtualCPUs {
            get {
                return ResourceManager.GetString("VirtualCPUs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workflow must have at least one step..
        /// </summary>
        internal static string WfEmptyStepCountError {
            get {
                return ResourceManager.GetString("WfEmptyStepCountError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No name provided for workflow. Please provide a name and try again..
        /// </summary>
        internal static string WfNameEmptyError {
            get {
                return ResourceManager.GetString("WfNameEmptyError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save failed. No type was provided for workflow..
        /// </summary>
        internal static string WfTypeEmptyError {
            get {
                return ResourceManager.GetString("WfTypeEmptyError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to When Retries Are Exhausted.
        /// </summary>
        internal static string WhenRetriesExhausted {
            get {
                return ResourceManager.GetString("WhenRetriesExhausted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Windows Optional Features.
        /// </summary>
        internal static string WindowsOptionalFeatures {
            get {
                return ResourceManager.GetString("WindowsOptionalFeatures", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wired Network.
        /// </summary>
        internal static string WiredNetwork {
            get {
                return ResourceManager.GetString("WiredNetwork", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to select smart groups to modify these.
        /// </summary>
        internal static string WorkflowDisabledCatalogTooltip
        {
            get
            {
                return ResourceManager.GetString("WorkflowDisabledCatalogTooltip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workflow does not exist or might have been deleted..
        /// </summary>
        internal static string WorkflowDoesNotExistOrMightBeDeleted {
            get {
                return ResourceManager.GetString("WorkflowDoesNotExistOrMightBeDeleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workflow Execution Status.
        /// </summary>
        internal static string WorkflowExecutionStatus {
            get {
                return ResourceManager.GetString("WorkflowExecutionStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workflow Paused Successfully.
        /// </summary>
        internal static string WorkflowPausedSuccessfully {
            get {
                return ResourceManager.GetString("WorkflowPausedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workflow Pause Failed. Try Again..
        /// </summary>
        internal static string WorkflowPauseFailedTryAgain {
            get {
                return ResourceManager.GetString("WorkflowPauseFailedTryAgain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Restore Defaults.
        /// </summary>
        internal static string WorkflowRestoreDefaults {
            get {
                return ResourceManager.GetString("WorkflowRestoreDefaults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workflow Resumed Successfully.
        /// </summary>
        internal static string WorkflowResumedSuccessfully {
            get {
                return ResourceManager.GetString("WorkflowResumedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workflow Resume Failed. Try Again..
        /// </summary>
        internal static string WorkflowResumeFailedTryAgain {
            get {
                return ResourceManager.GetString("WorkflowResumeFailedTryAgain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Retry Interval.
        /// </summary>
        internal static string WorkflowRetryInterval {
            get {
                return ResourceManager.GetString("WorkflowRetryInterval", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workflow Settings.
        /// </summary>
        internal static string WorkflowSettings {
            get {
                return ResourceManager.GetString("WorkflowSettings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configure the default settings for workflows. You can override these settings in individual workflows..
        /// </summary>
        internal static string WorkflowSettingsDesc {
            get {
                return ResourceManager.GetString("WorkflowSettingsDesc", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Devices will execute the workflow upon checkin..
        /// </summary>
        internal static string WorkflowSmartGroupDescription {
            get {
                return ResourceManager.GetString("WorkflowSmartGroupDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Device received the workflow but has not yet reported a workflow step status.
        /// </summary>
        internal static string WorkflowStatusNotEvaluatedInfo {
            get {
                return ResourceManager.GetString("WorkflowStatusNotEvaluatedInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Workflow Step.
        /// </summary>
        internal static string WorkflowStep {
            get {
                return ResourceManager.GetString("WorkflowStep", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string WorkflowTimeout {
            get {
                return ResourceManager.GetString("WorkflowTimeout", resourceCulture);
            }
        }
    }
}
