//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WanderingWiFi.AirWatch.Globalization.Resources.Content {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LabelValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WanderingWiFi.AirWatch.Globalization.Resources.Content.LabelValues", typeof(LabelValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledged.
        /// </summary>
        internal static string Acknowledged {
            get {
                return ResourceManager.GetString("Acknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgement only applies to Smartfolio for Required content..
        /// </summary>
        internal static string AcknowledgedNotRequired {
            get {
                return ResourceManager.GetString("AcknowledgedNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Repository Content.
        /// </summary>
        internal static string AdminRepositoryContent {
            get {
                return ResourceManager.GetString("AdminRepositoryContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow for viewing of Corporate File Servers.
        /// </summary>
        internal static string AllowCorporateFileServerViewing {
            get {
                return ResourceManager.GetString("AllowCorporateFileServerViewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are attempting to upload {0} files that are larger than the maximum allowed file size of {1} MB.  See Settings &gt; Admin &gt; Storage to alter the maximum file size from their default values. If you do not see the Storage option, you do not have access. You will need to contact an administrator with higher permissions to make the desired changes..
        /// </summary>
        internal static string ArgFilesLargerThanMaximumAllowedArgMessage {
            get {
                return ResourceManager.GetString("ArgFilesLargerThanMaximumAllowedArgMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Sync Admin Repositories.
        /// </summary>
        internal static string AutoSyncAdminRepositories {
            get {
                return ResourceManager.GetString("AutoSyncAdminRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string AutoTemplateDescription {
            get {
                return ResourceManager.GetString("AutoTemplateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Batch Import Feature can be used to load documents into the system in bulk. A template for this import is linked below for reference..
        /// </summary>
        internal static string BatchImportContentLockerExplanation {
            get {
                return ResourceManager.GetString("BatchImportContentLockerExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Content Platform can be enabled only at customer OG.
        /// </summary>
        internal static string CCPCanBeEnabledAtCustomerOgOnly {
            get {
                return ResourceManager.GetString("CCPCanBeEnabledAtCustomerOgOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Data Usage Exceeds {0} {1}.
        /// </summary>
        internal static string CellDataUsageExceedsArg {
            get {
                return ResourceManager.GetString("CellDataUsageExceedsArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Data Usage Exceeds {0} of Total Plan.
        /// </summary>
        internal static string CellDataUsageExceedsArgOfTotalPlan {
            get {
                return ResourceManager.GetString("CellDataUsageExceedsArgOfTotalPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Authentication.
        /// </summary>
        internal static string CertificateAuthentication {
            get {
                return ResourceManager.GetString("CertificateAuthentication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling use of a PIV-D Derived Credential requires Kerberos configuration in the Content Gateway settings..
        /// </summary>
        internal static string CertificateBasedAuthenticationTooltip {
            get {
                return ResourceManager.GetString("CertificateBasedAuthenticationTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload a third party public SSL certificate for devices to trust Content Gateway (must be in &apos;.pfx&apos; format and contain your public and private key pairs)..
        /// </summary>
        internal static string CGPublicSslCertificateTooltip {
            get {
                return ResourceManager.GetString("CGPublicSslCertificateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Repository Name for Managed Content.
        /// </summary>
        internal static string ChangeRepositoryName {
            get {
                return ResourceManager.GetString("ChangeRepositoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Certificate Chain.
        /// </summary>
        internal static string ClientCertificateChain {
            get {
                return ResourceManager.GetString("ClientCertificateChain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Content Platform.
        /// </summary>
        internal static string CloudContentPlatform {
            get {
                return ResourceManager.GetString("CloudContentPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Content Platform already configured for this customer OG. Client APIs can be used to interact with the platform.
        /// </summary>
        internal static string CloudContentPlatformConfigured {
            get {
                return ResourceManager.GetString("CloudContentPlatformConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloud Content Platform.
        /// </summary>
        internal static string CloudContentPlatformDescription {
            get {
                return ResourceManager.GetString("CloudContentPlatformDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Platform provides a unified access to an end user&apos;s content across various enterprise repositories where one might Content Platform provides a unified access to an end user&apos;s content across various enterprise repositories where one might persist the data. Click on the launch button to configure this customer OG to use the CCP endpoints..
        /// </summary>
        internal static string CloudContentPlatformInfo {
            get {
                return ResourceManager.GetString("CloudContentPlatformInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Gateway is not configured. Configure at {0} settings..
        /// </summary>
        internal static string ConfigureContentGateway {
            get {
                return ResourceManager.GetString("ConfigureContentGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Advanced Corporate File Servers.
        /// </summary>
        internal static string ContentAdvancedCorporateFileServers {
            get {
                return ResourceManager.GetString("ContentAdvancedCorporateFileServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls syncing of external content repository..
        /// </summary>
        internal static string ContentAdvancedCorporateFileServersHelp {
            get {
                return ResourceManager.GetString("ContentAdvancedCorporateFileServersHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Device.
        /// </summary>
        internal static string ContentDevice {
            get {
                return ResourceManager.GetString("ContentDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Content gateway configuration.
        /// </summary>
        internal static string ContentGatewayConfigurationNotSelected {
            get {
                return ResourceManager.GetString("ContentGatewayConfigurationNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Gateway Configuration Uid.
        /// </summary>
        internal static string ContentGatewayConfigurationUid {
            get {
                return ResourceManager.GetString("ContentGatewayConfigurationUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public SSL Certificate (required for Linux deployments).
        /// </summary>
        internal static string ContentGatewayPublicSslCertificate {
            get {
                return ResourceManager.GetString("ContentGatewayPublicSslCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace ONE Content App.
        /// </summary>
        internal static string ContentLocker {
            get {
                return ResourceManager.GetString("ContentLocker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content SSL Certificate.
        /// </summary>
        internal static string ContentSSLCertificate {
            get {
                return ResourceManager.GetString("ContentSSLCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature will be deprecated in an upcoming release. Share your feedback on this change at the {0}..
        /// </summary>
        internal static string CorporateFileServerDefaultMessage {
            get {
                return ResourceManager.GetString("CorporateFileServerDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Gateway Setting ID.
        /// </summary>
        internal static string CustomGatewaySettingID {
            get {
                return ResourceManager.GetString("CustomGatewaySettingID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected type and value did not match for the keys {0}..
        /// </summary>
        internal static string CustomGatewaySettingInvalidDataType {
            get {
                return ResourceManager.GetString("CustomGatewaySettingInvalidDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Gateway Settings.
        /// </summary>
        internal static string CustomGatewaySettings {
            get {
                return ResourceManager.GetString("CustomGatewaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        internal static string DeletedSucessfully {
            get {
                return ResourceManager.GetString("DeletedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deny List.
        /// </summary>
        internal static string DenyList {
            get {
                return ResourceManager.GetString("DenyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Controller.
        /// </summary>
        internal static string DomainController {
            get {
                return ResourceManager.GetString("DomainController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hostname or IP address of domain controller for the domain..
        /// </summary>
        internal static string DomainControllerTooltip {
            get {
                return ResourceManager.GetString("DomainControllerTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Content Gateway Configuration.
        /// </summary>
        internal static string DownloadContentGatewayConfiguration {
            get {
                return ResourceManager.GetString("DownloadContentGatewayConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Content Viewer Configuration.
        /// </summary>
        internal static string DownloadContentViewerConfiguration {
            get {
                return ResourceManager.GetString("DownloadContentViewerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Successful.
        /// </summary>
        internal static string DownloadSuccessful {
            get {
                return ResourceManager.GetString("DownloadSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EB.
        /// </summary>
        internal static string Eb {
            get {
                return ResourceManager.GetString("Eb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable, go to the {0} page. This feature will be deprecated in an upcoming release..
        /// </summary>
        internal static string ExternalRepositorySyncDeprecationMessage {
            get {
                return ResourceManager.GetString("ExternalRepositorySyncDeprecationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share your feedback on this change at the {0}..
        /// </summary>
        internal static string ExternalRepositorySyncShareFeedbackMessage {
            get {
                return ResourceManager.GetString("ExternalRepositorySyncShareFeedbackMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure.
        /// </summary>
        internal static string Failure {
            get {
                return ResourceManager.GetString("Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is disabled.
        /// </summary>
        internal static string FeatureIsDisabled {
            get {
                return ResourceManager.GetString("FeatureIsDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total file size (6GB) exceeded for multiple download..
        /// </summary>
        internal static string FileSizeExceededForMultiDownload {
            get {
                return ResourceManager.GetString("FileSizeExceededForMultiDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Status.
        /// </summary>
        internal static string FileStatus {
            get {
                return ResourceManager.GetString("FileStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace ONE UEM automatically configures file storage for SaaS customers. For on-premises customers, configure a dedicated server to {0}, internal apps, and managed content. This reduces the overall burden on the Workspace ONE UEM database and increases performance. Do not change your file storage server without migrating its current contents..
        /// </summary>
        internal static string FileStorageInformationMessageWithArg {
            get {
                return ResourceManager.GetString("FileStorageInformationMessageWithArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideas Portal.
        /// </summary>
        internal static string IdeasPortal {
            get {
                return ResourceManager.GetString("IdeasPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid template or denylist for {0}.
        /// </summary>
        internal static string InvalidBlacklistLink {
            get {
                return ResourceManager.GetString("InvalidBlacklistLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category {0} does not belong to any of the assigned Organization Group hierarchy.
        /// </summary>
        internal static string InvalidCategoryAssignment {
            get {
                return ResourceManager.GetString("InvalidCategoryAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid response format.
        /// </summary>
        internal static string InvalidResponseFormat {
            get {
                return ResourceManager.GetString("InvalidResponseFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain name in AD containing users. Domain must match UPN suffix. (ex. corp.test.com and user@corp.test.com) .
        /// </summary>
        internal static string KcdDomainTooltip {
            get {
                return ResourceManager.GetString("KcdDomainTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerberos authentication error. Please check the provided UPN..
        /// </summary>
        internal static string KerberosAuthenticationError {
            get {
                return ResourceManager.GetString("KerberosAuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kerberos configuration error. Please check KDC host, domain name and service account details..
        /// </summary>
        internal static string KerberosConfigurationError {
            get {
                return ResourceManager.GetString("KerberosConfigurationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate File Servers.
        /// </summary>
        internal static string LabelCorporateFileServers {
            get {
                return ResourceManager.GetString("LabelCorporateFileServers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed Content.
        /// </summary>
        internal static string ManagedContent {
            get {
                return ResourceManager.GetString("ManagedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed Content Delete.
        /// </summary>
        internal static string ManagedContentDelete {
            get {
                return ResourceManager.GetString("ManagedContentDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denied Link(s).
        /// </summary>
        internal static string ManualTemplateBlacklistedLinks {
            get {
                return ResourceManager.GetString("ManualTemplateBlacklistedLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        internal static string ManualTemplateLink {
            get {
                return ResourceManager.GetString("ManualTemplateLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ManualTemplateLinkAdd {
            get {
                return ResourceManager.GetString("ManualTemplateLinkAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository EndPoint(s).
        /// </summary>
        internal static string ManualTemplateRepoEndPoints {
            get {
                return ResourceManager.GetString("ManualTemplateRepoEndPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string ManualTemplateType {
            get {
                return ResourceManager.GetString("ManualTemplateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum selected file count (10) exceeded..
        /// </summary>
        internal static string MaxSelectedFileCountExceeded {
            get {
                return ResourceManager.GetString("MaxSelectedFileCountExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mem Configuration UId.
        /// </summary>
        internal static string MemConfigurationUId {
            get {
                return ResourceManager.GetString("MemConfigurationUId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NullValue.
        /// </summary>
        internal static string NullValue {
            get {
                return ResourceManager.GetString("NullValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PB.
        /// </summary>
        internal static string Pb {
            get {
                return ResourceManager.GetString("Pb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        internal static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Content can only be enabled at or below an Organization Group of Type &quot;Customer&quot;..
        /// </summary>
        internal static string PersonalContentCanOnlyBeEnabledAtCustomerLg {
            get {
                return ResourceManager.GetString("PersonalContentCanOnlyBeEnabledAtCustomerLg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Derived Credentials.
        /// </summary>
        internal static string PIVDDerivedCredentials {
            get {
                return ResourceManager.GetString("PIVDDerivedCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linux (Legacy).
        /// </summary>
        internal static string PlatformLinux {
            get {
                return ResourceManager.GetString("PlatformLinux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unified Access Gateway.
        /// </summary>
        internal static string PlatformUag {
            get {
                return ResourceManager.GetString("PlatformUag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows (Legacy).
        /// </summary>
        internal static string PlatformWindows {
            get {
                return ResourceManager.GetString("PlatformWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter name..
        /// </summary>
        internal static string PleaseEnterContentRepositoryTemplateName {
            get {
                return ResourceManager.GetString("PleaseEnterContentRepositoryTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter user repository name..
        /// </summary>
        internal static string PleaseEnterUserRepositoryName {
            get {
                return ResourceManager.GetString("PleaseEnterUserRepositoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Content Gateway with KCD settings..
        /// </summary>
        internal static string PleaseSelectContentGatewayWithKcdSettings {
            get {
                return ResourceManager.GetString("PleaseSelectContentGatewayWithKcdSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide User Principal Name for the AD user synced with external repository..
        /// </summary>
        internal static string ProvideADUserUPN {
            get {
                return ResourceManager.GetString("ProvideADUserUPN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        internal static string Repositories {
            get {
                return ResourceManager.GetString("Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        internal static string Repository {
            get {
                return ResourceManager.GetString("Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository test connection failed..
        /// </summary>
        internal static string RepositoryTestConnectionFailed {
            get {
                return ResourceManager.GetString("RepositoryTestConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Public SSL certificate is required for RFS with secure connection. Please upload the full certificate chain in &apos;.pfx&apos; format..
        /// </summary>
        internal static string RFSSSLCertificateRequiredWarning {
            get {
                return ResourceManager.GetString("RFSSSLCertificateRequiredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Signature Requests.
        /// </summary>
        internal static string SearchSignatureRequests {
            get {
                return ResourceManager.GetString("SearchSignatureRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content will use the settings defined in the selected Profiles. Configure your Profile by navigating to Apps &gt; Settings and Policies &gt; {0}.
        /// </summary>
        internal static string SecureContentLockerSettingsCustomizeMessage {
            get {
                return ResourceManager.GetString("SecureContentLockerSettingsCustomizeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content will use the default Application Settings &amp; Policies defined on the following pages:.
        /// </summary>
        internal static string SecureContentLockerSettingsDefaultMessage {
            get {
                return ResourceManager.GetString("SecureContentLockerSettingsDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AirWatch Managed Database.
        /// </summary>
        internal static string StorageTypeDatabase {
            get {
                return ResourceManager.GetString("StorageTypeDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UEM Managed.
        /// </summary>
        internal static string StorageTypeInternal {
            get {
                return ResourceManager.GetString("StorageTypeInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to store reports.
        /// </summary>
        internal static string StoreYourReports {
            get {
                return ResourceManager.GetString("StoreYourReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TB.
        /// </summary>
        internal static string Tb {
            get {
                return ResourceManager.GetString("Tb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content will display the Terms of Use selected in the below field. Create your own TOU by navigating to System &gt; {0}.
        /// </summary>
        internal static string TermsOfUseMessage {
            get {
                return ResourceManager.GetString("TermsOfUseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel Configuration Uid.
        /// </summary>
        internal static string TunnelConfigurationUid {
            get {
                return ResourceManager.GetString("TunnelConfigurationUid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Gateway services are now only available via the Unified Access Gateway. Legacy Linux and Windows versions of Content Gateway are no longer supported.
        ///.
        /// </summary>
        internal static string Uaginfomessage {
            get {
                return ResourceManager.GetString("Uaginfomessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete.
        /// </summary>
        internal static string UnableToDelete {
            get {
                return ResourceManager.GetString("UnableToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload not permitted, file size exceeds available storage..
        /// </summary>
        internal static string UploadNotAllowedOverQuota {
            get {
                return ResourceManager.GetString("UploadNotAllowedOverQuota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty file upload is not allowed.
        /// </summary>
        internal static string UploadNotPermittedEmptyFile {
            get {
                return ResourceManager.GetString("UploadNotPermittedEmptyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewed.
        /// </summary>
        internal static string Viewed {
            get {
                return ResourceManager.GetString("Viewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace ONE Content App.
        /// </summary>
        internal static string WorkspaceONEContentApp {
            get {
                return ResourceManager.GetString("WorkspaceONEContentApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace ONE Content Services.
        /// </summary>
        internal static string WS1ContentServices {
            get {
                return ResourceManager.GetString("WS1ContentServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YB.
        /// </summary>
        internal static string Yb {
            get {
                return ResourceManager.GetString("Yb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZB.
        /// </summary>
        internal static string Zb {
            get {
                return ResourceManager.GetString("Zb", resourceCulture);
            }
        }
    }
}
