#singletonServer: http://localhost:8091
singletonServer: https://g11n-vip-dev-1.eng.vmware.com:8090

enableCache: true
initializeCache: true
#unit: second
cacheExpiredTime: 0


defaultLocale: zh-Hans

localBundles: ""

name: GoClientTest
version: 1.0.0