#singletonServer: https://localhost:8090
singletonServer: https://g11n-vip-dev-1.eng.vmware.com:8090

enableCache: false
initializeCache: true
#unit: second
cacheExpiredTime: 50


defaultLocale: zh-Hans

localBundles: ""

name: GoClientTest
version: 1.0.0