//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WanderingWiFi.AirWatch.Globalization.Resources.DeviceManagement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LabelValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LabelValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WanderingWiFi.AirWatch.Globalization.Resources.DeviceManagement.LabelValues", typeof(LabelValues).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Tag.
        /// </summary>
        internal static string AddTag {
            get {
                return ResourceManager.GetString("AddTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grants permission to create a new tag.
        /// </summary>
        internal static string AddTagHelp {
            get {
                return ResourceManager.GetString("AddTagHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify an alphanumeric passcode to troubleshoot a device in admin mode. Tap the Hub icon on the login screeen 5 times to access admin mode..
        /// </summary>
        internal static string AdminModePasscodeHelpText {
            get {
                return ResourceManager.GetString("AdminModePasscodeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VMware Workspace ONE Intelligent Hub only collects information that is required to provide secure corporate access.
        /// </summary>
        internal static string AirwatchCannotSeeYourPersonalContent {
            get {
                return ResourceManager.GetString("AirwatchCannotSeeYourPersonalContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow PIN at Startup.
        /// </summary>
        internal static string AllowPinAtStartup {
            get {
                return ResourceManager.GetString("AllowPinAtStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Mode Passcode.
        /// </summary>
        internal static string AndroidSharedDeviceAdminModePasscode {
            get {
                return ResourceManager.GetString("AndroidSharedDeviceAdminModePasscode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Shared Device Mode.
        /// </summary>
        internal static string AndroidSharedDeviceMode {
            get {
                return ResourceManager.GetString("AndroidSharedDeviceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check in and check out shared Android devices using native Android capability or Workspace ONE Launcher. Native Android supports simpler use cases that don’t require much customization. Launcher supports UI customization for more complex use cases..
        /// </summary>
        internal static string AndroidSharedDeviceModeHelpText {
            get {
                return ResourceManager.GetString("AndroidSharedDeviceModeHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Catalog Support.
        /// </summary>
        internal static string AppCatalogSupport {
            get {
                return ResourceManager.GetString("AppCatalogSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Tags.
        /// </summary>
        internal static string AssignTags {
            get {
                return ResourceManager.GetString("AssignTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth Device.
        /// </summary>
        internal static string BluetoothDeviceMessageLabelAny {
            get {
                return ResourceManager.GetString("BluetoothDeviceMessageLabelAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Usage.
        /// </summary>
        internal static string CallUsageMessageLabelAny {
            get {
                return ResourceManager.GetString("CallUsageMessageLabelAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete an user that has a DEP registration record or if it&apos;s asscociated to a DEP profile.
        /// </summary>
        internal static string CannotDeleteUsersWithRegistrationRecord {
            get {
                return ResourceManager.GetString("CannotDeleteUsersWithRegistrationRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier Country Code.
        /// </summary>
        internal static string CarrierCountryCodeMessageLabelAny {
            get {
                return ResourceManager.GetString("CarrierCountryCodeMessageLabelAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cellular Data Usage.
        /// </summary>
        internal static string CellularDataUsageMessageLabelAny {
            get {
                return ResourceManager.GetString("CellularDataUsageMessageLabelAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chrome OS Device Removal.
        /// </summary>
        internal static string ChromeOsDeviceCleanup {
            get {
                return ResourceManager.GetString("ChromeOsDeviceCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable the Secure Startup option, which requires an initial PIN entry to boot up the device. If Secure Startup is already disabled, the device must be factory reset to enable it.  This feature applies only to Android devices that do not have file-based encryption..
        /// </summary>
        internal static string ClearDevicePasscodeDevicePageHelpInfo {
            get {
                return ResourceManager.GetString("ClearDevicePasscodeDevicePageHelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable Android Secure Startup, which requires an initial PIN entry to boot up the device. If disabled, users cannot enable Secure Startup during passcode setup. If Secure Startup is already disabled on the device, the device must be factory reset to enable it.  This feature applies only to Android devices that do not have file-based encryption..
        /// </summary>
        internal static string ClearDevicePasscodeSharedSettingsHelpInfo {
            get {
                return ResourceManager.GetString("ClearDevicePasscodeSharedSettingsHelpInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Admin Mode Passcode.
        /// </summary>
        internal static string ConfirmAndroidSharedDeviceAdminModePasscode {
            get {
                return ResourceManager.GetString("ConfirmAndroidSharedDeviceAdminModePasscode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action unenrolls and removes all managed enterprise resources from the selected device (including applications and profiles).  You cannot undo this action without re-enrolling this device..
        /// </summary>
        internal static string ConfirmEnterpriseWipeDeviceMessageChromeOs {
            get {
                return ResourceManager.GetString("ConfirmEnterpriseWipeDeviceMessageChromeOs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, export.
        /// </summary>
        internal static string ConfirmExport {
            get {
                return ResourceManager.GetString("ConfirmExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Confirmation.
        /// </summary>
        internal static string ConfirmOverwrite {
            get {
                return ResourceManager.GetString("ConfirmOverwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting this PPKG will overwrite any PPKGs for completed templates. Please ensure you download the previous PPKG before exporting this one. Are you sure you want to continue?.
        /// </summary>
        internal static string ConfirmOverwriteMessage {
            get {
                return ResourceManager.GetString("ConfirmOverwriteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The above collection areas are specific to VMware Workspace ONE Intelligent Hub, and may vary for corporate and personal devices.
        ///
        ///Contact your IT Administrator about any third-party applications that may allow your company to see additional personal/private information, and for a copy of all applicable internal policies..
        /// </summary>
        internal static string ContactAdminPrivacyNotice {
            get {
                return ResourceManager.GetString("ContactAdminPrivacyNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency Applications.
        /// </summary>
        internal static string DependencyApplications {
            get {
                return ResourceManager.GetString("DependencyApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Bulk Management assign Tags.
        /// </summary>
        internal static string DeviceBulkManagementAddTags {
            get {
                return ResourceManager.GetString("DeviceBulkManagementAddTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows user to assign tags to device(s) in bulk..
        /// </summary>
        internal static string DeviceBulkManagementAddTagsHelp {
            get {
                return ResourceManager.GetString("DeviceBulkManagementAddTagsHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty space cannot be used as a reason..
        /// </summary>
        internal static string DeviceDeleteWhiteSpaceReason {
            get {
                return ResourceManager.GetString("DeviceDeleteWhiteSpaceReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Phone Number.
        /// </summary>
        internal static string DevicePhoneNumberMessageLabelAny {
            get {
                return ResourceManager.GetString("DevicePhoneNumberMessageLabelAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage device provisioning packages.
        /// </summary>
        internal static string DeviceProvisioningMenuDescription {
            get {
                return ResourceManager.GetString("DeviceProvisioningMenuDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provisioning.
        /// </summary>
        internal static string DeviceProvisioningMenuTitle {
            get {
                return ResourceManager.GetString("DeviceProvisioningMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different Model Replacement.
        /// </summary>
        internal static string DifferentModelReplacement {
            get {
                return ResourceManager.GetString("DifferentModelReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Encrypted Package.
        /// </summary>
        internal static string DownloadEncryptedPackage {
            get {
                return ResourceManager.GetString("DownloadEncryptedPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Provisioning Files.
        /// </summary>
        internal static string DownloadProvisioningFiles {
            get {
                return ResourceManager.GetString("DownloadProvisioningFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download windows phone agent.
        /// </summary>
        internal static string DownloadWindowsPhoneAgent {
            get {
                return ResourceManager.GetString("DownloadWindowsPhoneAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is already in use. Please choose another name..
        /// </summary>
        internal static string DuplicatePackageFound {
            get {
                return ResourceManager.GetString("DuplicatePackageFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Provisioning Package.
        /// </summary>
        internal static string EditProvisioningPackage {
            get {
                return ResourceManager.GetString("EditProvisioningPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education Certificate Renewal Job.
        /// </summary>
        internal static string EducationCertificateRenewalJob {
            get {
                return ResourceManager.GetString("EducationCertificateRenewalJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Auto-Discovery.
        /// </summary>
        internal static string EmailDiscovery {
            get {
                return ResourceManager.GetString("EmailDiscovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Domain Registration Failure.
        /// </summary>
        internal static string EmailDomainRegistrationFailure {
            get {
                return ResourceManager.GetString("EmailDomainRegistrationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Domain Registration Success.
        /// </summary>
        internal static string EmailDomainRegistrationSuccess {
            get {
                return ResourceManager.GetString("EmailDomainRegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No applications found..
        /// </summary>
        internal static string EmptyApplicationList {
            get {
                return ResourceManager.GetString("EmptyApplicationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty enrollment session. Please try again..
        /// </summary>
        internal static string EmptyEnrollmentSessionPleaseTryAgain {
            get {
                return ResourceManager.GetString("EmptyEnrollmentSessionPleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new provisioning packages will appear here..
        /// </summary>
        internal static string EmptyPackageList {
            get {
                return ResourceManager.GetString("EmptyPackageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export single encrypted PPKG bundle to provision local devices with configurations, settings, and applications..
        /// </summary>
        internal static string EncryptedPackageDescription {
            get {
                return ResourceManager.GetString("EncryptedPackageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypted Package.
        /// </summary>
        internal static string EncryptedPackageTitle {
            get {
                return ResourceManager.GetString("EncryptedPackageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address.
        /// </summary>
        internal static string Enrollmentemailaddress {
            get {
                return ResourceManager.GetString("Enrollmentemailaddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Username.
        /// </summary>
        internal static string Enrollmentemailusername {
            get {
                return ResourceManager.GetString("Enrollmentemailusername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter characters shown above.
        /// </summary>
        internal static string EnterCharactersShownAbove {
            get {
                return ResourceManager.GetString("EnterCharactersShownAbove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise wipe failed..
        /// </summary>
        internal static string EnterpriseWipeFailed {
            get {
                return ResourceManager.GetString("EnterpriseWipeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Reason field is required when requesting an enterprise wipe..
        /// </summary>
        internal static string EnterpriseWipeReasonRequired {
            get {
                return ResourceManager.GetString("EnterpriseWipeReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enterprise wipe succeeded..
        /// </summary>
        internal static string EnterpriseWipeSucceeded {
            get {
                return ResourceManager.GetString("EnterpriseWipeSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting....
        /// </summary>
        internal static string ExportInProgress {
            get {
                return ResourceManager.GetString("ExportInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another provisioning package export is already in progress. Either save your template and export later, or wait until the other export completes..
        /// </summary>
        internal static string ExportLater {
            get {
                return ResourceManager.GetString("ExportLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed loading unmanaged Profile payload.
        /// </summary>
        internal static string FailedLoadingUnmanagedProfilePayload {
            get {
                return ResourceManager.GetString("FailedLoadingUnmanagedProfilePayload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download request failed, please try again later..
        /// </summary>
        internal static string FailedToDownload {
            get {
                return ResourceManager.GetString("FailedToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export.
        /// </summary>
        internal static string FailedToExport {
            get {
                return ResourceManager.GetString("FailedToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature is currently not supported..
        /// </summary>
        internal static string FeatureNotSupported {
            get {
                return ResourceManager.GetString("FeatureNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS.
        /// </summary>
        internal static string GPSMessageLabelAny {
            get {
                return ResourceManager.GetString("GPSMessageLabelAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address and Group ID both are required.
        /// </summary>
        internal static string GroupIDAndEmailRequired {
            get {
                return ResourceManager.GetString("GroupIDAndEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some applications were deleted or modified after this package was created. Please review the list of selected applications to ensure it is complete..
        /// </summary>
        internal static string InactiveAppsFound {
            get {
                return ResourceManager.GetString("InactiveAppsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoke Agent.
        /// </summary>
        internal static string InvokeAgent {
            get {
                return ResourceManager.GetString("InvokeAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher.
        /// </summary>
        internal static string LauncherSharedDeviceMode {
            get {
                return ResourceManager.GetString("LauncherSharedDeviceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed Installations.
        /// </summary>
        internal static string ManagedInstallations {
            get {
                return ResourceManager.GetString("ManagedInstallations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple enrollment users associated with the given email address.
        /// </summary>
        internal static string MultipleEnrollmentUsersForEmail {
            get {
                return ResourceManager.GetString("MultipleEnrollmentUsersForEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native.
        /// </summary>
        internal static string NativeSharedDeviceMode {
            get {
                return ResourceManager.GetString("NativeSharedDeviceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Provisioning Package.
        /// </summary>
        internal static string NewProvisioningPackage {
            get {
                return ResourceManager.GetString("NewProvisioningPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No enrollment user is associated with the given email address.
        /// </summary>
        internal static string NoEnrollmentUserForEmail {
            get {
                return ResourceManager.GetString("NoEnrollmentUserForEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No organization group was found for the entered group ID.
        /// </summary>
        internal static string NoOrganizationGroupForGroupId {
            get {
                return ResourceManager.GetString("NoOrganizationGroupForGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Transform Selected.
        /// </summary>
        internal static string NoTransformSelected {
            get {
                return ResourceManager.GetString("NoTransformSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not working?.
        /// </summary>
        internal static string NotWorking {
            get {
                return ResourceManager.GetString("NotWorking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export PPKG and XML files to pre-load devices with configurations, settings, and applications at the OEM Facility..
        /// </summary>
        internal static string OEMProvisioningDescription {
            get {
                return ResourceManager.GetString("OEMProvisioningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory Provisioning.
        /// </summary>
        internal static string OEMProvisioningTitle {
            get {
                return ResourceManager.GetString("OEMProvisioningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onboarding Method.
        /// </summary>
        internal static string OnboardingMethod {
            get {
                return ResourceManager.GetString("OnboardingMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onboarding Methods.
        /// </summary>
        internal static string OnboardingMethods {
            get {
                return ResourceManager.GetString("OnboardingMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not authorized to enroll at the given organization group.
        /// </summary>
        internal static string OrganizationGroupInvalidForEnrollmentUser {
            get {
                return ResourceManager.GetString("OrganizationGroupInvalidForEnrollmentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An existing Windows Provisioning Package (PPKG) export request is in progress. Please wait for the export to complete..
        /// </summary>
        internal static string PackageInProgress {
            get {
                return ResourceManager.GetString("PackageInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success! Creating provisioning package in progress. Check back later for download link..
        /// </summary>
        internal static string PackageSaved {
            get {
                return ResourceManager.GetString("PackageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Application.
        /// </summary>
        internal static string PersonalApplicationMessageLabelAny {
            get {
                return ResourceManager.GetString("PersonalApplicationMessageLabelAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform Confirmation.
        /// </summary>
        internal static string PlatformConfirmation {
            get {
                return ResourceManager.GetString("PlatformConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm if you are using an iPad to avoid problems registering and installing apps..
        /// </summary>
        internal static string PromptForiPadandMAC {
            get {
                return ResourceManager.GetString("PromptForiPadandMAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote Control Access.
        /// </summary>
        internal static string RemoteControlAccess {
            get {
                return ResourceManager.GetString("RemoteControlAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaced.
        /// </summary>
        internal static string Replaced {
            get {
                return ResourceManager.GetString("Replaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested.
        /// </summary>
        internal static string Requested {
            get {
                return ResourceManager.GetString("Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retiring Device.
        /// </summary>
        internal static string RetiringDevice {
            get {
                return ResourceManager.GetString("RetiringDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roaming Status.
        /// </summary>
        internal static string RoamingStatusMessageLabelAny {
            get {
                return ResourceManager.GetString("RoamingStatusMessageLabelAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same Model Replacement.
        /// </summary>
        internal static string SameModelReplacement {
            get {
                return ResourceManager.GetString("SameModelReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save And Export.
        /// </summary>
        internal static string SaveAndExport {
            get {
                return ResourceManager.GetString("SaveAndExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, save for later.
        /// </summary>
        internal static string SaveForLater {
            get {
                return ResourceManager.GetString("SaveForLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Applications.
        /// </summary>
        internal static string SelectedApplications {
            get {
                return ResourceManager.GetString("SelectedApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Staging Mode.
        /// </summary>
        internal static string SelectStagingMode {
            get {
                return ResourceManager.GetString("SelectStagingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Usage.
        /// </summary>
        internal static string SMSUsageMessageLabelAny {
            get {
                return ResourceManager.GetString("SMSUsageMessageLabelAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staging is enabled for the given enrollment user.
        /// </summary>
        internal static string StagingIsEnabledForEnrollmentUser {
            get {
                return ResourceManager.GetString("StagingIsEnabledForEnrollmentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow end users to access system apps.
        /// </summary>
        internal static string SystemAppsToggleHelpText {
            get {
                return ResourceManager.GetString("SystemAppsToggleHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Logs.
        /// </summary>
        internal static string SystemLogs {
            get {
                return ResourceManager.GetString("SystemLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Logs Privacy Notice.
        /// </summary>
        internal static string SystemLogsPrivacyNoticeMessageLabel {
            get {
                return ResourceManager.GetString("SystemLogsPrivacyNoticeMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap here to retry.
        /// </summary>
        internal static string TapHereToRetry {
            get {
                return ResourceManager.GetString("TapHereToRetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        internal static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Installer Transform.
        /// </summary>
        internal static string TransformLabel {
            get {
                return ResourceManager.GetString("TransformLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A transform is a collection of changes applied to an installation of an MSI. Select an available transform file (MST) that will be used during installation..
        /// </summary>
        internal static string TransformToolTipText {
            get {
                return ResourceManager.GetString("TransformToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform.
        /// </summary>
        internal static string TransformToolTipTitle {
            get {
                return ResourceManager.GetString("TransformToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory Type.
        /// </summary>
        internal static string UnattendAdJoinLabel {
            get {
                return ResourceManager.GetString("UnattendAdJoinLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type of AD Join to use. Based on this selection the form below will facilitate a particular AD Join unattend.xml.
        /// </summary>
        internal static string UnattendAdJoinText {
            get {
                return ResourceManager.GetString("UnattendAdJoinText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Admin Logon.
        /// </summary>
        internal static string UnattendAutoAdminLogonLabel {
            get {
                return ResourceManager.GetString("UnattendAutoAdminLogonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A one-time administrator logon is needed to enroll the device. Auto admin logon has been turned on and the local administrator account is now required to be set up.
        /// </summary>
        internal static string UnattendAutoAdminLogonText {
            get {
                return ResourceManager.GetString("UnattendAutoAdminLogonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Config File.
        /// </summary>
        internal static string UnattendBuildConfigFile {
            get {
                return ResourceManager.GetString("UnattendBuildConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the password for the administrator account.
        /// </summary>
        internal static string UnattendBuildInAdminText {
            get {
                return ResourceManager.GetString("UnattendBuildInAdminText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Password.
        /// </summary>
        internal static string UnattendBuiltInAdminLabel {
            get {
                return ResourceManager.GetString("UnattendBuiltInAdminLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Name.
        /// </summary>
        internal static string UnattendComputerNameLabel {
            get {
                return ResourceManager.GetString("UnattendComputerNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Name (Random).
        /// </summary>
        internal static string UnattendComputerNamePlaceholder {
            get {
                return ResourceManager.GetString("UnattendComputerNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Local User.
        /// </summary>
        internal static string UnattendCreateLocalUserLabel {
            get {
                return ResourceManager.GetString("UnattendCreateLocalUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting &quot;Yes&quot; will pre-create a local user account. Selecting &quot;No&quot; will prompt the user to create one during OOBE..
        /// </summary>
        internal static string UnattendCreateLocalUserText {
            get {
                return ResourceManager.GetString("UnattendCreateLocalUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Name.
        /// </summary>
        internal static string UnattendDomainNameLabel {
            get {
                return ResourceManager.GetString("UnattendDomainNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name of the Domain the client will be joined to.
        /// </summary>
        internal static string UnattendDomainNameText {
            get {
                return ResourceManager.GetString("UnattendDomainNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD Organization Unit (OU).
        /// </summary>
        internal static string UnattendDomainOuLabel {
            get {
                return ResourceManager.GetString("UnattendDomainOuLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be in format &quot;OU=,OU=,DC=Company,DC=com&quot;.
        /// </summary>
        internal static string UnattendDomainOuText {
            get {
                return ResourceManager.GetString("UnattendDomainOuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Password.
        /// </summary>
        internal static string UnattendDomainPasswordLabel {
            get {
                return ResourceManager.GetString("UnattendDomainPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password of the Active Directory domain-join account..
        /// </summary>
        internal static string UnattendDomainPasswordText {
            get {
                return ResourceManager.GetString("UnattendDomainPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain Username.
        /// </summary>
        internal static string UnattendDomainUserLabel {
            get {
                return ResourceManager.GetString("UnattendDomainUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username of an Active Directory account with domain-join privileges..
        /// </summary>
        internal static string UnattendDomainUserText {
            get {
                return ResourceManager.GetString("UnattendDomainUserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unattend XML.
        /// </summary>
        internal static string UnattendDownloadMarkup {
            get {
                return ResourceManager.GetString("UnattendDownloadMarkup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPKG.
        /// </summary>
        internal static string UnattendDownloadPackage {
            get {
                return ResourceManager.GetString("UnattendDownloadPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Administrator Account.
        /// </summary>
        internal static string UnattendEnableBuiltInAdminLabel {
            get {
                return ResourceManager.GetString("UnattendEnableBuiltInAdminLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable the built-in administrator account. This account is disabled by default. When using Auto Admin Logon, the default administrator account must be enabled.
        /// </summary>
        internal static string UnattendEnableBuiltInAdminText {
            get {
                return ResourceManager.GetString("UnattendEnableBuiltInAdminText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Logon Commands.
        /// </summary>
        internal static string UnattendFirstLogonCmdLabel {
            get {
                return ResourceManager.GetString("UnattendFirstLogonCmdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add commands that will automatically run the first time a user logs on (Requires the user to have local admin privileges).
        /// </summary>
        internal static string UnattendFirstLogonCmdText {
            get {
                return ResourceManager.GetString("UnattendFirstLogonCmdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Hong Kong).
        /// </summary>
        internal static string UnattendLocaleChineseHongKong {
            get {
                return ResourceManager.GetString("UnattendLocaleChineseHongKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (China).
        /// </summary>
        internal static string UnattendLocaleChinesePrc {
            get {
                return ResourceManager.GetString("UnattendLocaleChinesePrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (simplified).
        /// </summary>
        internal static string UnattendLocaleChineseSimplified {
            get {
                return ResourceManager.GetString("UnattendLocaleChineseSimplified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (Taiwan).
        /// </summary>
        internal static string UnattendLocaleChineseTaiwan {
            get {
                return ResourceManager.GetString("UnattendLocaleChineseTaiwan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese (traditional).
        /// </summary>
        internal static string UnattendLocaleChineseTraditional {
            get {
                return ResourceManager.GetString("UnattendLocaleChineseTraditional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string UnattendLocaleEnglish {
            get {
                return ResourceManager.GetString("UnattendLocaleEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English - UK.
        /// </summary>
        internal static string UnattendLocaleEnglishUk {
            get {
                return ResourceManager.GetString("UnattendLocaleEnglishUk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English - US.
        /// </summary>
        internal static string UnattendLocaleEnglishUs {
            get {
                return ResourceManager.GetString("UnattendLocaleEnglishUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string UnattendLocaleFrench {
            get {
                return ResourceManager.GetString("UnattendLocaleFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French - Canada.
        /// </summary>
        internal static string UnattendLocaleFrenchCanada {
            get {
                return ResourceManager.GetString("UnattendLocaleFrenchCanada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French - France.
        /// </summary>
        internal static string UnattendLocaleFrenchFrance {
            get {
                return ResourceManager.GetString("UnattendLocaleFrenchFrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string UnattendLocaleGerman {
            get {
                return ResourceManager.GetString("UnattendLocaleGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string UnattendLocaleItalian {
            get {
                return ResourceManager.GetString("UnattendLocaleItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string UnattendLocaleJapanese {
            get {
                return ResourceManager.GetString("UnattendLocaleJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korean.
        /// </summary>
        internal static string UnattendLocaleKorean {
            get {
                return ResourceManager.GetString("UnattendLocaleKorean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region and Keyboard.
        /// </summary>
        internal static string UnattendLocaleLabel {
            get {
                return ResourceManager.GetString("UnattendLocaleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string UnattendLocalePortuguese {
            get {
                return ResourceManager.GetString("UnattendLocalePortuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (Brazil).
        /// </summary>
        internal static string UnattendLocalePortugueseBrazil {
            get {
                return ResourceManager.GetString("UnattendLocalePortugueseBrazil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese (Portugal).
        /// </summary>
        internal static string UnattendLocalePortuguesePortugal {
            get {
                return ResourceManager.GetString("UnattendLocalePortuguesePortugal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string UnattendLocaleSpanish {
            get {
                return ResourceManager.GetString("UnattendLocaleSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish - Mexico.
        /// </summary>
        internal static string UnattendLocaleSpanishMexico {
            get {
                return ResourceManager.GetString("UnattendLocaleSpanishMexico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish - Spain.
        /// </summary>
        internal static string UnattendLocaleSpanishSpain {
            get {
                return ResourceManager.GetString("UnattendLocaleSpanishSpain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the input language and keyboard layout available based on operating system language selected above..
        /// </summary>
        internal static string UnattendLocaleText {
            get {
                return ResourceManager.GetString("UnattendLocaleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Administrator.
        /// </summary>
        internal static string UnattendLocalUserAdminLabel {
            get {
                return ResourceManager.GetString("UnattendLocalUserAdminLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes is required for AirWatch enrollment to automatically kick off. During login, the user will see an AirWatch window pop up to enter enrollment credentials.
        /// </summary>
        internal static string UnattendLocalUserAdminText {
            get {
                return ResourceManager.GetString("UnattendLocalUserAdminText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Username.
        /// </summary>
        internal static string UnattendLocalUserNameLabel {
            get {
                return ResourceManager.GetString("UnattendLocalUserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the username of the local user.
        /// </summary>
        internal static string UnattendLocalUserNameText {
            get {
                return ResourceManager.GetString("UnattendLocalUserNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local User Password.
        /// </summary>
        internal static string UnattendLocalUserPasswordLabel {
            get {
                return ResourceManager.GetString("UnattendLocalUserPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If no password is specified, system will prompt user to change password on first sign in.
        /// </summary>
        internal static string UnattendLocalUserPasswordText {
            get {
                return ResourceManager.GetString("UnattendLocalUserPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operating System Language.
        /// </summary>
        internal static string UnattendMediaLanguageLabel {
            get {
                return ResourceManager.GetString("UnattendMediaLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the language of the Operating System installation media provided to OEM.
        /// </summary>
        internal static string UnattendMediaLanguageText {
            get {
                return ResourceManager.GetString("UnattendMediaLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Active Directory - No Premium.
        /// </summary>
        internal static string UnattendModeAzureAdNoPrem {
            get {
                return ResourceManager.GetString("UnattendModeAzureAdNoPrem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Active Directory - Premium.
        /// </summary>
        internal static string UnattendModeAzureAdPrem {
            get {
                return ResourceManager.GetString("UnattendModeAzureAdPrem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workgroup.
        /// </summary>
        internal static string UnattendModeWorkgroup {
            get {
                return ResourceManager.GetString("UnattendModeWorkgroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Command.
        /// </summary>
        internal static string UnattendNewCmdLabel {
            get {
                return ResourceManager.GetString("UnattendNewCmdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-premises Active Directory Join.
        /// </summary>
        internal static string UnattendOnPremAdJoin {
            get {
                return ResourceManager.GetString("UnattendOnPremAdJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OOBE Configuration.
        /// </summary>
        internal static string UnattendOobeSectionLabel {
            get {
                return ResourceManager.GetString("UnattendOobeSectionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Key.
        /// </summary>
        internal static string UnattendProductKeyLabel {
            get {
                return ResourceManager.GetString("UnattendProductKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Windows product key is a sequence of five letters or numbers, repeated five times and seperated by dashes. Example: &quot;12345-54CDE-XYZ78-ONM98-456TY&quot;.
        /// </summary>
        internal static string UnattendProductKeyText {
            get {
                return ResourceManager.GetString("UnattendProductKeyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Organization.
        /// </summary>
        internal static string UnattendRegisteredOrgLabel {
            get {
                return ResourceManager.GetString("UnattendRegisteredOrgLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will show up in system information..
        /// </summary>
        internal static string UnattendRegisteredOrgText {
            get {
                return ResourceManager.GetString("UnattendRegisteredOrgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Owner.
        /// </summary>
        internal static string UnattendRegisteredOwnerLabel {
            get {
                return ResourceManager.GetString("UnattendRegisteredOwnerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will show up in system information.
        /// </summary>
        internal static string UnattendRegisteredOwnerText {
            get {
                return ResourceManager.GetString("UnattendRegisteredOwnerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Windows 10 Consumer Apps.
        /// </summary>
        internal static string UnattendRemoveConsumerAppsLabel {
            get {
                return ResourceManager.GetString("UnattendRemoveConsumerAppsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabling this prevents consumer apps (i.e. Candy Crush) from appearing in Windows 10. It is only supported by entering an Enterprise or Education product key below. Requires Windows version 1511 or higher.
        /// </summary>
        internal static string UnattendRemoveConsumerAppsText {
            get {
                return ResourceManager.GetString("UnattendRemoveConsumerAppsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save package, please verify the form and try again..
        /// </summary>
        internal static string UnattendSaveFailed {
            get {
                return ResourceManager.GetString("UnattendSaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EULA Page.
        /// </summary>
        internal static string UnattendShowEulaLabel {
            get {
                return ResourceManager.GetString("UnattendShowEulaLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;Show&quot; to show the Microsoft Software License Terms page during OOBE.
        /// </summary>
        internal static string UnattendShowEulaText {
            get {
                return ResourceManager.GetString("UnattendShowEulaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region and Keyboard Settings.
        /// </summary>
        internal static string UnattendShowLocaleSettingsLabel {
            get {
                return ResourceManager.GetString("UnattendShowLocaleSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting &quot;Show&quot; will show the Region and Keyboard Settings page during OOBE. Selecting &quot;Hide&quot; hides it and requires you to select the from available locale in the drop-down below..
        /// </summary>
        internal static string UnattendShowLocaleSettingsText {
            get {
                return ResourceManager.GetString("UnattendShowLocaleSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Account Settings.
        /// </summary>
        internal static string UnattendShowOnlineAccountLabel {
            get {
                return ResourceManager.GetString("UnattendShowOnlineAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;Show&quot; to show the online account screen. This allows you to sign in using a Microsoft account..
        /// </summary>
        internal static string UnattendShowOnlineAccountText {
            get {
                return ResourceManager.GetString("UnattendShowOnlineAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Settings.
        /// </summary>
        internal static string UnattendShowPrivacyLabel {
            get {
                return ResourceManager.GetString("UnattendShowPrivacyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &quot;Show&quot; to prompt the user to select Privacy settings during OOBE. Selecting &quot;Hide&quot; uses Express settings and hides it..
        /// </summary>
        internal static string UnattendShowPrivacyText {
            get {
                return ResourceManager.GetString("UnattendShowPrivacyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Synchronous Commands.
        /// </summary>
        internal static string UnattendSyncCmdLabel {
            get {
                return ResourceManager.GetString("UnattendSyncCmdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can add commands that will automatically run at the end of the Windows setup process, but before any user login.
        /// </summary>
        internal static string UnattendSyncCmdText {
            get {
                return ResourceManager.GetString("UnattendSyncCmdText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Configuration.
        /// </summary>
        internal static string UnattendSystemConfigurationSection {
            get {
                return ResourceManager.GetString("UnattendSystemConfigurationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Notify.
        /// </summary>
        internal static string UnattendUacAlwaysNotify {
            get {
                return ResourceManager.GetString("UnattendUacAlwaysNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string UnattendUacDefault {
            get {
                return ResourceManager.GetString("UnattendUacDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string UnattendUacDisabled {
            get {
                return ResourceManager.GetString("UnattendUacDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled but do not Notify.
        /// </summary>
        internal static string UnattendUacEnableButDoNotNotify {
            get {
                return ResourceManager.GetString("UnattendUacEnableButDoNotNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Account Control.
        /// </summary>
        internal static string UnattendUacLabel {
            get {
                return ResourceManager.GetString("UnattendUacLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notify Without Dimming Desktop.
        /// </summary>
        internal static string UnattendUacNotifyWithoutDimmingDesktop {
            get {
                return ResourceManager.GetString("UnattendUacNotifyWithoutDimmingDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the type of User Account Control.
        /// </summary>
        internal static string UnattendUacText {
            get {
                return ResourceManager.GetString("UnattendUacText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input.
        /// </summary>
        internal static string UnattendValidationInvalidInput {
            get {
                return ResourceManager.GetString("UnattendValidationInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required and cannot have more than {0} characters.
        /// </summary>
        internal static string UnattendValidationMaxLength {
            get {
                return ResourceManager.GetString("UnattendValidationMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must create a local user which is a member of the administrators group, or enable the built-in administrator.
        /// </summary>
        internal static string UnattendValidationNoAdminUser {
            get {
                return ResourceManager.GetString("UnattendValidationNoAdminUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid product key.
        /// </summary>
        internal static string UnattendValidationProductKey {
            get {
                return ResourceManager.GetString("UnattendValidationProductKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field cannot be empty.
        /// </summary>
        internal static string UnattendValidationRequired {
            get {
                return ResourceManager.GetString("UnattendValidationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Configuration Tool for Provisioning. Be sure to provide values for all required fields to enable the build config file button.
        /// </summary>
        internal static string UnattendWelcome {
            get {
                return ResourceManager.GetString("UnattendWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workgroup.
        /// </summary>
        internal static string UnattendWorkgroupLabel {
            get {
                return ResourceManager.GetString("UnattendWorkgroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name of the Workgroup the client will be joined to.
        /// </summary>
        internal static string UnattendWorkgroupText {
            get {
                return ResourceManager.GetString("UnattendWorkgroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment OG.
        /// </summary>
        internal static string UnattendWs1OgLabel {
            get {
                return ResourceManager.GetString("UnattendWs1OgLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your enrollment OG Group ID. If you have SAML turned on, ensure you setup a separate &quot;Staging&quot; OG with SAML turned off. You can mouse over the OG at the top of the Workspace ONE console to get the Group ID..
        /// </summary>
        internal static string UnattendWs1OgText {
            get {
                return ResourceManager.GetString("UnattendWs1OgText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workspace ONE Enrollment.
        /// </summary>
        internal static string UnattendWs1Section {
            get {
                return ResourceManager.GetString("UnattendWs1Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Server.
        /// </summary>
        internal static string UnattendWs1ServerLabel {
            get {
                return ResourceManager.GetString("UnattendWs1ServerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your enrollment server URL. It is found in All Settings --&gt; System --&gt; Advanced --&gt; Site URLs under MDM Enrollment URL. Only include the core URL. For example, vmwarelab.awmdm.com.
        /// </summary>
        internal static string UnattendWs1ServerText {
            get {
                return ResourceManager.GetString("UnattendWs1ServerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staging Account.
        /// </summary>
        internal static string UnattendWs1StagingAccountLabel {
            get {
                return ResourceManager.GetString("UnattendWs1StagingAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staging Password.
        /// </summary>
        internal static string UnattendWs1StagingAccountPasswordLabel {
            get {
                return ResourceManager.GetString("UnattendWs1StagingAccountPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staging account &quot;password&quot; as specified on the same page as the staging account. If the password includes special characters ( &apos;&amp;&apos;, &apos;&gt;&apos;, or &apos;&lt;&apos; ) , factory provisioning workflows that use this account for enrollment will fail. To change the password, go to the Users page..
        /// </summary>
        internal static string UnattendWs1StagingAccountPasswordText {
            get {
                return ResourceManager.GetString("UnattendWs1StagingAccountPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the staging account found in All Settings --&gt; Devices &amp; Users --&gt; Windows --&gt; Windows Desktop --&gt; Staging &amp; Provisioning in the UPN field.
        /// </summary>
        internal static string UnattendWs1StagingAccountText {
            get {
                return ResourceManager.GetString("UnattendWs1StagingAccountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmanaged Profiles.
        /// </summary>
        internal static string UnmanagedProfilesMessageLabelAny {
            get {
                return ResourceManager.GetString("UnmanagedProfilesMessageLabelAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Device.
        /// </summary>
        internal static string USBDeviceMessageLabelAny {
            get {
                return ResourceManager.GetString("USBDeviceMessageLabelAny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a group ID?.
        /// </summary>
        internal static string UserEnrollmentAndEnter {
            get {
                return ResourceManager.GetString("UserEnrollmentAndEnter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User enrollment is not enabled in the specified organization group.
        /// </summary>
        internal static string UserEnrollmentNotEnabledInOg {
            get {
                return ResourceManager.GetString("UserEnrollmentNotEnabledInOg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the &apos;Settings&apos; app, locate and tap &quot;Enroll in your company&quot;.
        /// </summary>
        internal static string UserEnrollmentSettingsMessage {
            get {
                return ResourceManager.GetString("UserEnrollmentSettingsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use email address.
        /// </summary>
        internal static string UserEnrollmentUseEmailAddress {
            get {
                return ResourceManager.GetString("UserEnrollmentUseEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        internal static string UserPasswordIsRequired {
            get {
                return ResourceManager.GetString("UserPasswordIsRequired", resourceCulture);
            }
        }
    }
}
