on:
  workflow_call:
    inputs:
      fail-on-error:
        required: true
        type: boolean

jobs:
  woke:
    name: woke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Woke
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: ${{ inputs.fail-on-error }}
          # The woke rule is turned off, but still shows the output
          woke-args: --config https://via.vmw.com/its-woke-rules -o text --disable-default-rules
